bluebanquise/bluebanquise

README.md, roles/ADDON_slurm/addon/slurm.yml, roles/ADDON_slurm/tasks/main.yml, roles/ADDON_slurm/vars/main.yml
Hello JK.
Someone asked for OpenHPC compatibility.
All HPC scientific packages from OpenHPC are autonomous, so ok for them. Only issue I see is with slurm version.
Then, BlueBanquise will be able to replace provisioning of OpenHPC, but be compatible with it's rpms.
Is it ok for you this way ?
Ox
=> Adapting slurm to handle both packaging. Allow OpenHPC slurm.

roles/core/pxe_stack/tasks/main.yml
Hi,
In '/var/www/html/preboot_execution_environment/equipment_ipxe_configurations/' directory
[root@mngt0-1 ]# ll /var/www/html/preboot_execution_environment/equipment_ipxe_configurations/
total 20
-rw-r--r--. 1 apache apache 427 Nov 28 11:12 minimal.ipxe
-rwxr-xr-x. 1 apache apache 891 Nov 28 11:44 _typeC.ipxe
-rwxr-xr-x. 1 apache apache 961 Nov 28 11:12 _typeM.ipxe
The *.ipxe file generated by the template isn't correct.
I have fixed it with this patch.
Best regards
=> Update role pxe_stack main.yml

roles/core/pxe_stack/templates/menu.ipxe.j2
Hi,
http://10.0.0.240/preboot_execution_environment/bin/grub2_efi_autofind.img... No such file or directory (http://ipxe.org/2d0c618e)
Regards
=> fail during the UEFI node boot phase

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Hi,
When I write an inventory file that describes the options 61, I have issue:
```
failed: [mngt0-1] (item=ice1-1) => changed=false
ansible_loop_var: item
item: ice1-1
msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''dhcp'''
```
I have fixed this issue like this.
Kind regards
=> advanced_dhcp_server role fails with opt61

roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/opensuse_leap_15.yml, roles/core/repositories_client/tasks/redhat_7.yml, roles/core/repositories_client/tasks/redhat_8.yml, roles/core/repositories_client/tasks/ubuntu_18.yml
Commit d60214be replaced system_repositories with repositories in the
examples and tasks for CentOS 8. Update the repositories_client tasks
for other OS as well.
=> Fix: rename of system_repositories in tasks

resources/examples/simple_cluster/inventory/group_vars/all/all_equipments, resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/authentication.yml, resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/README.md, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/accelerated_mode.yml, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/equipment.yml, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/icebergs.yml, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/internal_variables.yml, resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/network.yml
Commit 4c24c8f7 introduced two symbolic links in the simple_cluster
inventory, with relative paths to the multi_icebergs_cluster inventory.
The "Configure BlueBanquise" documentation provides commands to copy the
simple_cluster inventory as the new inventory. Doing so breaks the
relative symlinks and makes the inventory unusable.
This commit fixes this by removing the symlinks and copying the
directories of the multi_icebergs_cluster inventory to the
simple_cluster inventory.
=> Fix: replace symlinks from simple_cluster examples

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2
By default, the pxe_ip defines the next-server to use for both the TFTP
and HTTP/iPXE services which muse be hosted on the same server.
It is now possible to use a different next-server for HTTP/iPXE by
defining a new service parameter pxe_http_ip, thus the HTTP server for
ipxe scripts can be run on a separate server than the TFTP service.
The PXE chain remains unchanged: the first next-server obtained at boot
time is pxe_ip and it allows to load the iPXE bluebanquise ROM through
TFTP. This ROM will send a new request to the DHCP to get the
next-server to use for the HTTP/iPXE service. If pxe_http_ip is set,
then this is the IP address that will be used as next-server. Otherwise,
the default will be the pxe_ip.
Solve #60.
=> Feature: alternate next-server for HTTP/iPXE

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml, roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml, roles/core/repositories_client/tasks/redhat_7.yml, roles/core/repositories_client/tasks/redhat_8.yml
Allow to modify some settings for the repo, be it a system repository or
an external repository.
List of settings: name, baseurl, enabled, gpgcheck, gpgkey and proxy.
System repositories, internal to the cluster, can use the same
configuration syntax than previously:
repositories:
- bluebanquise
- os
It can be expanded to change settings for a repo with a dict, using
YAML's flow styles or block styles:
repositories:
- bluebanquise
- { name: 'os', gpgcheck: 1 }  # Flow style
- name: epel                   # Block style
gpgcheck: 1
Additional repositories can either be added to the repositories.yml or
external.yml configuration files, to logically segregate internal and
external repositories.
external_repositories:
- name: epel
baseurl: …
=> Feat: make yum repositories more configurable

roles/core/ssh_master/tasks/main.yml
Hi,
We noticed that some tag names were not consistent between the different roles.
I propose this patch.
Best regards
=> consistency of tag names in roles

.github/workflows/static_analysis.yml
Use GitHub Actions to run a workflow for static code analysis.
The workflow runs ansible-lint and flake8. Some tests are ignored for now.
=> ci: add workflow for static code analysis

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/repositories.yml, resources/examples/simple_cluster/inventory/group_vars/all/general_settings/repositories.yml, roles/core/repositories_client/handlers/main.yml, roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml
This feature allows to disable the CentOS repositories enabled by
default after the installation of the OS. It can be enabled or disabled
with the boolean parameter remove_distro_repositories.
If the parameter is not defined, the repositories are untouched to keep
current behavior. In the examples, the parameter defaults to True
because it is good practice to set up a local mirror when we have a lot
of systems.
=> feat: Disable CentOS distro repositories

resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
With commit ec9e900c, the external_repositories should either be undefined, or defined with repositories configuration. I forgot to update the simple_cluster examples.
=> fix: comment external_repositories

roles/core/pxe_stack/tasks/main.yml
The recursive task was changing mod of the files in the directory, while
following task are setting different mod for the same files after.
With this change, a new run of the pxe_stack role will not report change
if the configuration of the target is up-to-date.
=> fix: [pxe_stack] remove recursive setting of perms

roles/addons/nic_nmcli/tasks/main.yml, roles/addons/ofed/tasks/main.yml, roles/addons/ofed_sm/tasks/main.yml, roles/addons/openldap_client/tasks/main.yml, roles/addons/openldap_server/tasks/main.yml, roles/addons/prometheus_client/tasks/main.yml, roles/addons/prometheus_server/tasks/main.yml, roles/addons/slurm/tasks/main.yml, roles/advanced-core/advanced_dhcp_server/tasks/main.yml, roles/core/dns_server/tasks/services_centos_7.yml, roles/core/dns_server/tasks/services_redhat_8.yml, roles/core/dns_server/tasks/services_ubuntu_18.yml, roles/core/nfs_client/tasks/main.yml
Most of the services should support the enable_services and
start_services parameters. Also add the tag service.
Closes #95
=> fix: add support to enable and start services

bluebanquise.spec, tools/bluebanquise-playbook
```
Usage:
bluebanquise-playbook -l
bluebanquise-playbook -p <playbook> [-n <nodeset>] [ansible-playbook parameters]
Runs Ansible playbooks, executing the defined playbook on the targeted nodes.
Options:
-h              print this help and exit
-l              list available playbooks
-p <playbook>   run the playbook
-n <nodeset>    list of target nodes, accept nodeset(1) patterns
```
=> feat: create wrapper command bluebanquise-playbook

resources/examples/simple_cluster/playbooks/login1.yml, resources/examples/simple_cluster/playbooks/management1.yml
Allow to use `--extra-vars target=foo` whatever the playbook.
=> fix: add target variable to example playbooks

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Hello,
When we define several networks (ice1-2, ice1-3, ...), the `dhcpd.subnet.conf.j2` template generate many **trailing whitespace and blank line**s in DHCP configuration files.
This is not a problem to run the DHCP service, but the configuration files generate is too big and not very clean.
For fix this issue, please merge my patch.
Regards,
=> [1.1.2] Trailing whitespace in dhcpd.subnet.conf.j2

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
DHCPD doesn't work with multi-subnets and mutli-hosts
Hello,
Sometimes we need to have multiple host machine interfaces in several different subnet.
in this case, the DHCP service does not start. 
It indicates that you can't have more than one host-name.
In fact the host-names are identical but this is prohibited by the DHCP service operation.
Inventory example:
```
equipment_typeM:
hosts:
mynode:
enp0s3:
ip4: 10.11.0.1
mac: 08:00:27:84:e3:35
ens3f0:
ip4: 192.168.1.254
mac: 90:e2:ba:e1:04:9e
network: ice1-2
ens3f1:
ip4: 192.168.0.254
mac: 90:e2:ba:e1:04:9f
network: ice1-3
```
With this inventory, the DHCP file generated is :
```
mynode-ice1-1 {
option host-name "mynode";
hardware ethernet XX:XX:XX:XX:XX; 
fixed-address 10.0.0.2;
}
mynode-ice1-2 {
option …
```
=> [1.2.0] DHCPD doesn't work with multi-subnets and mutli-hosts

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Hello,
Sometimes we need to have multiple host machine interfaces in several different subnet.
in this case, the DHCP service does not start. 
It indicates that you can't have more than one host-name.
In fact the host-names are identical but this is prohibited by the DHCP service operation.
Inventory example:
```
equipment_typeM:
hosts:
mynode:
enp0s3:
ip4: 10.11.0.1
mac: 08:00:27:84:e3:35
ens3f0:
ip4: 192.168.1.254
mac: 90:e2:ba:e1:04:9e
network: ice1-2
ens3f1:
ip4: 192.168.0.254
mac: 90:e2:ba:e1:04:9f
network: ice1-3
```
With this inventory, the DHCP file generated is :
```
mynode-ice1-1 {
option host-name "mynode";
hardware ethernet 08:00:27:84:e3:35; 
fixed-address 10.11.0.1;
}
mynode-ice1-2 {
option host-name "mynode";
hardware ethernet …
```
=> [1.1.2] DHCPD doesn't work with multi-subnets and mutli-hosts

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
When a second file /etc/dhcp/dhcpd.{{item}}.conf is generated, the dhcpd service crashes.
Indeed, there are whitespaces before the declaration of the hosts.
```
[root@pm-mgt0 nodes]# /usr/sbin/dhcpd -t -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid
Internet Systems Consortium DHCP Server 4.3.6
Copyright 2004-2017 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
WARNING: Host declarations are global. They are not limited to the scope you declared them in.
/etc/dhcp/dhcpd.ice1-2.conf line 0: whitespace too long, buffer overflow.
^
Exiting
```
=> [master] [advanced_dhcp_server] whitespace too long, buffer overflow.

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2, roles/core/dhcp_server/templates/dhcpd.subnet.conf.j2
Hi
When we define several networks (ice1-2, ice1-3, ...) , the dhcpd.subnet.conf.j2 template generate many trailing whitespace in DHCP configuration files.
This is not a problem to run the DHCP service, but the configuration files generate is too big and not very clean.
Regards
=> [stable-1.2] Trailing whitespace in dhcpd.subnet.conf.j2

roles/core/display_tuning/.yamllint, roles/core/display_tuning/molecule/default/INSTALL.rst, roles/core/display_tuning/molecule/default/converge.yml, roles/core/display_tuning/molecule/default/molecule.yml, roles/core/display_tuning/molecule/default/prepare.yml, roles/core/display_tuning/molecule/default/verify.yml, roles/core/display_tuning/tasks/main.yml, roles/core/dns_client/.yamllint, roles/core/dns_client/molecule/default/INSTALL.rst, roles/core/dns_client/molecule/default/converge.yml, roles/core/dns_client/molecule/default/molecule.yml, roles/core/dns_client/molecule/default/prepare.yml, roles/core/dns_client/molecule/default/verify.yml, roles/core/dns_client/vars/main.yml
- Added molecule test in display_tuning.
- Added molecule test in dns_client - warning the testing is limited to linters since /etc/resolv.conf cannot be touched within a container.
=> Molecule test for display tunning and dns client

bluebanquise.spec
After many tries, simply removing from the source all the files we don't want to ship is the more efficient and simple way.
rpmbuild tested and working when molecule, .ansible-lint and .yamllint are present.
=> Fixing spec file to remove CICD files from RPM

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/security.yml, resources/examples/simple_cluster/inventory/group_vars/all/security.yml, roles/core/ssh_master/readme.rst, roles/core/ssh_master/templates/config.j2
Set security.ssh.hostkey_checking=false to apply the following
parameters to the hosts in /root/.ssh/config:
StrictHostKeyChecking no
UserKnownHostsFile=/dev/null
Default to false if not defined to keep backward compatibility with existing setup.
Set to true in example inventories for new setup.
=> feat: security.ssh.hostkey_checking=true|false

roles/core/conman/tasks/main.yml, roles/core/conman/templates/conman.conf.j2, roles/core/conman/vars/RedHat_7.yml, roles/core/conman/vars/main.yml
Alternative to #172 
Check OS info from facts instead of inventory
Create a new variables `execpath` and get its value from the vars/
directory using `with_first_found`.
Search vars in:
- `<distribution>_<major>.yml`    # eg. CentOS_8.yml
- `<os_family>_<major>.yml`       # eg. RedHat_8.yml
- `<distribution>.yml`            # eg. CentOS.yml
- `<os_family>.yml`               # eg. RedHat.yml
=> fix: create variable execpath for conman.conf.j2

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml, resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml, roles/core/dns_server/templates/forward.j2, roles/core/dns_server/templates/reverse.j2
Fixes several caveats with the zone templates:
- Add $ORIGIN
- Remove useless Address record for the domain
- Remove inventory_hostname defined twice (explicitly + in the loop)
- Remove external_hosts, cannot be defined in the zone
Closes: #146
=> fix: improve DNS forward and reverse templates

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml, resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml, roles/core/dns_server/templates/forward.j2, roles/core/dns_server/templates/reverse.j2
Fixes several caveats with the zone templates:
- Add $ORIGIN
- Remove useless Address record for the domain
- Remove inventory_hostname defined twice (explicitly + in the loop)
- Remove external_hosts, cannot be defined in the zone
Closes: #146
(cherry picked from commit 1c1ea2d7970afcdd0f6cdfbd3ce22fadcfd99cab)
=> fix: improve DNS forward and reverse templates (#158)

roles/core/dns_server/handlers/main.yml, roles/core/dns_server/tasks/main.yml
Fix a bug introduced in ea0f6b7f, I forgot the file handlers/main.yml.
Also update `skip: true` to remove a warning reported by ansible-lint.
=> fix: correct loop in dns_server handlers

roles/core/repositories_client/readme.rst, roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml, roles/core/repositories_client/tasks/redhat_8.yml
This is a rework of 37b824c.
Centos 7:
Disable default repositories since the content of the ISO DVD is copied
in the os/ directory.
CentOS 8:
Instead of disabling the default OS repositories then configure new ones
in different files, use yum_repository parameter `file` to replace
existing configuration for BaseOS and AppStream.
Disable the Extras repository which is enabled by default but not
shipped with the ISO DVD. If one need to add the Extras repo, I would
recommend to add it to the inventory like any other repository.
Remove the now useless tunable `remove_distro_repositories`.
This commit also changes the logic to split `os` to `BaseOS` and
`AppStream` for CentOS/RHEL 8.
=> fix: disable CentOS default repositories

resources/documentation/install_first_management.rst, resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml, resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_SMP/equipment_profile.yml, resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_compute/equipment_profile.yml, resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_login/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/equipment_typeC/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/equipment_typeL/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/equipment_typeM/equipment_profile.yml, roles/core/pxe_stack/readme.rst, roles/core/pxe_stack/templates/equipment_profile.ipxe.j2, roles/core/pxe_stack/vars/main.yml
Make equipment_profile.operating_system.distribution_version optional.
If not defined, the pxe_stack role will default to the value of
distribution_major_version to set the images-root path.
=> feat: default to major distro for pxe boot images

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml, resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml, roles/core/pxe_stack/files/osdeploy/centos_7.ipxe, roles/core/pxe_stack/files/osdeploy/centos_8.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe, roles/core/pxe_stack/templates/equipment_profile.ipxe.j2, roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml, roles/core/repositories_client/tasks/redhat_7.yml, roles/core/repositories_client/tasks/redhat_8.yml, roles/core/repositories_client/templates/environment.j2
For admins who need to manage several environments (prod/staging) for
their repositories, it is now possible to define the new parameter
equipment_profile.operating_system.repositories_environment in the
inventory.
The new url for boot images and packages repositories will be:
.. code-block:: bash
Environment    Distribution    Version   Architecture    Repository
+                 +          +       +               +
|                 |          +--+    |               |
+--------------+  +--------+    |    |    +----------+
|           |    |    |    |
v           v    v    v    v
/var/www/html/repositories/production/centos/7/x86_64/os/
=> feat: add optional param repositories_environment

.gitignore
There is a proposal to create a virtual environment to develop and run
molecule tests in #165. There is no need to track the content of this
directory in git.
=> feat: add venv-molecule directory to .gitignore

.github/workflows/molecule-actions.yml, resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice1-1.yml, resources/examples/simple_cluster/playbooks/management1.yml, roles/advanced-core/advanced_dhcp_server/readme.rst, roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2, roles/advanced-core/advanced_dhcp_server/vars/main.yml, roles/core/ansible/readme.rst, roles/core/ansible/tasks/main.yml, roles/core/ansible/vars/main.yml, roles/core/dhcp_server/readme.rst, roles/core/dhcp_server/templates/dhcpd.networks.conf.j2, roles/core/dhcp_server/vars/main.yml, roles/core/dns_client/readme.rst, roles/core/dns_client/templates/resolv.conf.j2, roles/core/dns_client/vars/main.yml, roles/core/dns_server/molecule/default/converge.yml, roles/core/dns_server/molecule/default/molecule.yml, roles/core/dns_server/readme.rst, roles/core/dns_server/tasks/main.yml, roles/core/dns_server/tasks/master.yml, roles/core/dns_server/templates/forward.j2, roles/core/dns_server/templates/forward.soa.j2, roles/core/dns_server/templates/named.conf.j2, roles/core/dns_server/templates/reverse.j2, roles/core/dns_server/templates/reverse.soa.j2, roles/core/dns_server/vars/main.yml
PR for #100 
May be easier to review per commit.
Commit 1:
feat: configure several DNS servers in the clients
Allow to configure a list of several name servers in the dns_ip
parameter of a network:
dns_ip:
- 10.11.0.1
- 10.11.0.2
Update the dns_client role to create as much nameserver entries in
/etc/resolv.conf.
Update the dhcp_server and advanced_dhcp_server roles to add all the
dns_ip entries to domain-name-servers.
Enable jinja2's lstrip_blocks to indent the j2 templates without
indenting the destination file.
Commit 2:
feat: named listen-on local ipv4 address
Do not listen on all the dns_ip IPv4 addresses but only on those
already configured on the host.
Commit 3:
feat: add support for slave DNS servers
The master DNS is the first element of the dns_ip in the primary
management …
=> feat: dns server slaves

roles/core/log_server/molecule/default/verify.yml, roles/core/log_server/vars/RedHat_7.yml, roles/core/log_server/vars/RedHat_8.yml
Use of seport in the role requires:
- libselinux-python
- policycoreutils-python
PR for EL-like only (SELinux support).
Also removed an ineffective unit test.
=> Fix: log server seport deps

roles/advanced-core/advanced_dhcp_server/tasks/main.yml, roles/advanced-core/advanced_dhcp_server/vars/RedHat_7.yml, roles/advanced-core/advanced_dhcp_server/vars/RedHat_8.yml, roles/core/dhcp_server/tasks/main.yml, roles/core/dhcp_server/vars/RedHat_7.yml, roles/core/dhcp_server/vars/RedHat_8.yml, roles/core/dns_server/tasks/main.yml, roles/core/dns_server/vars/RedHat.yml, roles/core/log_server/tasks/main.yml, roles/core/log_server/vars/main.yml, roles/core/nfs_server/tasks/main.yml, roles/core/nfs_server/vars/RedHat.yml, roles/core/pxe_stack/tasks/main.yml, roles/core/pxe_stack/vars/CentOS_8.yml, roles/core/pxe_stack/vars/RedHat_7.yml, roles/core/pxe_stack/vars/RedHat_8.yml, roles/core/repositories_server/tasks/main.yml, roles/core/repositories_server/vars/RedHat.yml, roles/core/time/tasks/main.yml, roles/core/time/vars/RedHat.yml
If equipment_profile.firewall is true, the roles will add the relevant services to the firewall's default zone. In RHEL/CentOS, the firewall defaults to public zone.
For EL-like only. Can be extended to OpenSuse/Ubuntu later.
This PR focus on core and advanced-core roles only.
List of services per role:
- dhcp_server/advanced_dhcp_server:
- dhcp
- dns_server:
- dns
- log_server:
- syslog
- rsh (for syslog 514/tcp)
- nfs_server:
- nfs
- rpc-bind
- pxe_stack:
- http
- tftp
- repositories_server:
- http
- time:
- ntp
I don't consider `ssh_master` because:
1. The ssh service is already in the services of the default zone
2. The role does not configure the sshd service
For each role, one can override the default zone (public) by setting `${rolename}_firewall_zone`. For example, if one wants to …
=> fix: open services in firewall's public zone

.github/workflows/molecule-actions-core-bluebanquise.yml, .github/workflows/molecule-actions-core-repositories_client.yml, .github/workflows/molecule-actions-core-time.yml, .github/workflows/molecule-actions.yml, roles/addons/clustershell/molecule/default/molecule.yml, roles/addons/clustershell/molecule/default/prepare.yml, roles/addons/users_basic/molecule/default/molecule.yml, roles/addons/users_basic/molecule/default/prepare.yml, roles/core/bluebanquise/molecule/default/molecule.yml, roles/core/bluebanquise/molecule/default/prepare.yml, roles/core/conman/molecule/default/molecule.yml, roles/core/display_tuning/molecule/default/molecule.yml, roles/core/display_tuning/molecule/default/prepare.yml, roles/core/dns_client/molecule/default/molecule.yml, roles/core/dns_client/molecule/default/prepare.yml, roles/core/dns_server/molecule/default/molecule.yml, roles/core/dns_server/molecule/default/prepare.yml, roles/core/log_client/molecule/default/molecule.yml, roles/core/log_client/molecule/default/prepare.yml, roles/core/log_server/molecule/default/molecule.yml, roles/core/log_server/molecule/default/prepare.yml, roles/core/repositories_client/molecule/default/molecule.yml, roles/core/time/molecule/default/molecule.yml, roles/core/time/molecule/default/prepare.yml
Use our own docker images for molecule tests.
The main purpose is to prepare the support of OpenSUSE Leap. It will also help to solve some drawbacks with previous images.
=> ci: update platforms image for molecule tests

.github/workflows/static_analysis.yml, ansible.cfg
Use relative paths in ansible.cfg, as proposed in #182.
=> fix: use relative paths in ansible.cfg

roles/addons/diskless/files/disklessset.py
- disable cache
- patch nfs staging to golden process
- removing hard coded releasever in dnf install commands
- disable selinux in livenet kernel cmdline
Known issues :
- image creation fail when repositories_releasever var is not set (dnf var should be generated with distribution_major_version in repositories_client role instead of removing the file)
=> Fix disklessset

tools/inventory-converter-1.3-network_interfaces.py
flake8:
- 2 E265 block comment should start with '# '
- 4 E302 expected 2 blank lines, found 1
- 1 E305 expected 2 blank lines after class or function definition,
found 1
=> fix: code cleanup in inventory converter helper

tools/bluebanquise-playbook
When a list of nodes is provided with -n, run ansible-playbook with the
parameter --limit.
Remove support of --extra-vars target=nodeset. If
`hosts: {{ target }}` is found in the playbook, print a deprecation
error and exit.
Related to changes in #252.
=> fix: use --limit in bluebanquise-playbook

roles/core/repositories_client/molecule/default/molecule.yml, roles/core/repositories_client/readme.rst, roles/core/repositories_client/tasks/deprecation.yml, roles/core/repositories_client/tasks/main.yml, roles/core/repositories_client/vars/main.yml
This will print a `fail` message with `ignore_errors: yes` when `external_repositories` is defined in the inventory.
Fixes #268
=> feat: deprecate external_repositories

tools/inventory-converter-1.3-network_interfaces.py
CentOS 8 ship with PyYAML 3.12 while I used some features introduced
with 5.1, which are incompatible. See yaml/pyyaml#265.
It appears I tested it in my virtualenv setup with latest PyYAML 5.3.1.... :-1:
=> fix: make converter compatible with older PyYAML

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml
I thought it was removed in #252.
=> fix: remove external_repositories from multi icebergs inventory

internal/group_vars/all/j2_variables/network.yml, roles/core/ssh_master/templates/config.j2
Errors appear when a bond is required
Some roles fails using _j2_node_main_network_ and _j2_node_main_network_interface_ when the network is not defined for an interface. 
I'm using this template :
```
- interface: bond0
type: bond
vlan: false
bond_options: "mode=4 xmit_hash_policy=layer3+4 miimon=100 lacp_rate=1"
ip4: 10.11.0.1
- interface: ens5f0
type: bond-slave
master: bond0
- interface: ens5f1
type: bond-slave
master: bond0
```
=> fix missing checks on j2 network vars

roles/core/ssh_master/templates/config.j2
Missing check, leads to fails when some hosts could just be skipped but still be in the inventory.
=> Fix ssh master template

roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml, roles/core/repositories_client/tasks/redhat_7.yml, roles/core/repositories_client/tasks/redhat_8.yml
baseurl_prefix fact is defined with multi-line format for readability,
but the value must remain single line (no \n, no spaces).
Fixes #292.
=> fix: define baseurl_prefix as single line value

roles/addons/diskless/files/disklessset.py, roles/addons/diskless/readme.rst, roles/addons/diskless/tasks/main.yml
This PR implements some fixes and quick and dirty enhancements for the disklessset tool.
I fixed some bugs identified during testing of the tool:
1. 'Remove an image' action was not implemented
2. livenet image size was not user-friendly (ask for 1MB to create a 1GB image)
3. crash in load_kernel_list() when more than one file was found in the directory
4. over-consumption of disk space with the image_working_directory being copied next to the squashfs.img
5. crash in menus or submenus when no kernel or image are found
6. install disklessset after its requirements: a user reported crash of disklessset because these directory don't exist (might be HA related)
I added the features below:
1. inject a custom SSH public key to the livenet image: temporary solution to provide SSH key-based …
=> Enhance disklessset livenet

.github/workflows/rpmbuild-action.yml
We need to trigger this for PR as well. Otherwise some changes can break the rpm build and we cannot see this before merge to master. (https://github.com/bluebanquise/bluebanquise/runs/902731210)
=> ci: trigger Test RPM build for pull request

roles/addons/diskless/files/disklessset.py, roles/core/pxe_stack/files/osdeploy/centos_7.ipxe, roles/core/pxe_stack/files/osdeploy/centos_8.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
Add imgstat to see useful data before booting.
See https://ipxe.org/cmd/imgstat
I will update the other files if others are ok with this small add.
=> Call imgstat in ipxe files to get image report

roles/addons/diskless/files/disklessset.py
This change allows to create several images in parallel. Each image now has its own working directory. If a working dir already exists, it is removed.
Move the base directory from /root/ to /var/tmp/.
Do not mount the rootfs image to /mnt. Use image_working_directory/mnt instead.
=> fix: create a per-image diskless working dir

roles/core/pxe_stack/files/bootset.py
```
text
firstboot --enable
```
=> feat: display kickstart file of node with bootset

roles/addons/diskless/files/disklessset.py
Several fixes and improvements for images metadata in disklesset.
Add more information to metadata:
- timestamp
- status of SELinux (boolean)
- sha256 sum
- image size (in MiB)
fix: update handling of image metadata files
- Rename image_data.yml to image_metadata.yml since this file holds metadata of the diskless image.
- Remove the `image_data` key from the yaml file since it is useless.
- Read/write image metadata with yaml library.
fix: use images_path and os.path.join()
- Define the images path with new variable `images_path` (similar to `kernels_path`).
- Use os.path.join over string concatenation:
- 'dir1/'+dir2+'file' -> os.path.join('dir1', dir2, 'file')
- Replace most os.system() calls by appropriate methods:
- os.system('rm -Rf') -> shutil.rmtree()
- os.system('mkdir') -> …
=> fix: diskless metadata

roles/core/pxe_stack/templates/nodes_parameters.yml.j2
The macro node_main_nic returns a string encoded as unicode, which
breaks the rendering with Python 2. Since the macro is used once in the
template, remove it and use its logic in the for-loop.
Fixes: #328
Let's use Jinja2 for what it does best: templating. :relieved:
=> fix: drop macro node_main_nic from pxe_stack

roles/core/conman/tasks/main.yml, roles/core/log_server/tasks/main.yml, roles/core/nfs_client/tasks/main.yml
Spotted by ansible-lint's rule E208. (#317)
Set mode 750 for /var/log/{conman,rsyslog}.
Skip the test for the nfs_client mount point.
=> fix: define mode for directories

resources/documentation/monitoring/prometheus.rst
added start_services and enable_services because if the two vars are not set, the playbooks prometheus_client and prometheus_server will crash
=> Added vars for the playbook of prometheus_client and prometheus_server

roles/core/time/templates/chrony.conf.j2
jinja2 2.7 does not support test 'is gt'.
Fixes: #329
=> fix: use '>' instead of 'gt' in j2 templates

roles/core/firewall/tasks/main.yml
Identified during testing of 1.3-RC2: after enabling the firewall for some tests, I noticed a new run of my playbook which includes role firewall did not disable the service.
If ep_firewall is False, do not omit the state but ensure the service is stopped.
Note: I turned ep_firewall to True to enable the firewall for my test.
=> fix: stop firewall service if ep_firewall = False

roles/core/conman/tasks/main.yml
conman service needs this tunable when SELinux is enabled on the host.
=> fix: enable SELinux daemons_use_tty for conman

.github/workflows/molecule-actions-addons-clustershell.yml, .github/workflows/molecule-actions-addons-root_password.yml, .github/workflows/molecule-actions-addons-users_basic.yml, .github/workflows/molecule-actions-core-bluebanquise.yml, .github/workflows/molecule-actions-core-conman.yml, .github/workflows/molecule-actions-core-display_tuning.yml, .github/workflows/molecule-actions-core-dns_client.yml, .github/workflows/molecule-actions-core-dns_server.yml, .github/workflows/molecule-actions-core-firewall.yml, .github/workflows/molecule-actions-core-log_client.yml, .github/workflows/molecule-actions-core-log_server.yml, .github/workflows/molecule-actions-core-repositories_client.yml, .github/workflows/molecule-actions-core-ssh_master.yml, .github/workflows/molecule-actions-core-time.yml, .github/workflows/static_analysis.yml
This reverts commit ac1b811c5c2852d5f804bc65d994d95b5deebc28.
Draft PR to troubleshoot the issues with CI after new ansible, molecule and ansible-lint releases.
=> Revert "ci: do not install ansible 2.9.12"

CHANGELOG.md, resources/packaging/bluebanquise.spec
Draft PR to prepare 1.3 release. :package: 
**TODO before merge:**
fix: bump rpm version to 1.3.0
doc: update changelog for 1.3
- new network_interfaces sructure
- merge of networks in a single file
- rename all_equipment -> equipment_all
- removal of dicts equipment_profile/authentication
- ep_access_control is not a boolean anymore
I did not document the [breaking change for diskless metatada](https://github.com/bluebanquise/bluebanquise/pull/313#issuecomment-675135315). (role was not usable/stable enough in previous releases)
List of new roles (to add to CHANGELOG.md):
- core/access_control
- core/bluebanquise
- core/firewall
- advanced-core/advanced_dns_server
- addons/powerman
- addons/root_password
- addons/sssd
Any additional input is welcome. :smiley:
=> Prepare 1.3

roles/core/pxe_stack/files/bootset.py
Instead of running restorecon for each ipxe file in the for-loop, run a recursive restorecon once all the files are written.
Benchmark of the tool at scale demonstrated poor performance.
```
[root@management1 ~]# find /var/www/html/preboot_execution_environment/nodes/ -name node\* -delete
[root@management1 ~]# echo 3 > /proc/sys/vm/drop_caches
[root@management1 ~]# cat /etc/bluebanquise/pxe/pxe_parameters.yml
pxe_parameters:
apache_uid: apache
apache_gid: apache
ansible_selinux_status: disabled
[root@management1 ~]# time bootset -n node[00001-80000] -q -b osdeploy
real    1m10.953s
user    0m48.383s
sys     0m19.544s
```
```
[root@management1 ~]# find /var/www/html/preboot_execution_environment/nodes/ -type f -name node\* -delete
[root@management1 ~]# echo 3 > /proc/sys/vm/drop_caches …
```
=> fix: enhance performance of bootset at scale

roles/core/hosts_file/templates/hosts.j2
alias were not generated due to \n at the end of the maccro
=> fix alias in hosts_file role

roles/core/pxe_stack/files/bootset.py
Instead of running restorecon for each ipxe file in the for-loop, run a
recursive restorecon once all the files are written.
(cherry picked from commit 78443c6703b3b81a8847025880de899c17863502)
=> fix: enhance performance of bootset at scale (#362)

roles/core/hosts_file/templates/hosts.j2
alias were not generated due to \n at the end of the maccro
(cherry picked from commit 68701b7a69dfa867ce5947369bff98a3a51d15e3)
=> fix alias in hosts_file role (#359)

roles/addons/diskless/readme.rst
Current documentation did not allowed to chose an equipment profile for the diskless image.
Also simplified the ansible-playbook execution line.
=> Fix: Add equipment_profiles ability to diskless chroot

roles/addons/diskless/readme.rst
* Fix: Add equipment_profiles ability to diskless chroot
Current documentation did not allowed to chose an equipment profile for the diskless image.
Also simplified the ansible-playbook execution line.
* Fix: Typo correction on diskless readme
(cherry picked from commit bee08024b0c180d053dc1dac90dcfb05d9660c13)
=> Fix: Add equipment_profiles ability to diskless chroot (#354)

.github/TEST_MATRIX.md, .github/workflows/molecule-actions-addons-grafana.yml, resources/packaging/bluebanquise.spec, roles/addons/grafana/.yamllint, roles/addons/grafana/molecule/default/INSTALL.rst, roles/addons/grafana/molecule/default/converge.yml, roles/addons/grafana/molecule/default/molecule.yml, roles/addons/grafana/molecule/default/prepare.yml, roles/addons/grafana/molecule/default/verify.yml, roles/addons/grafana/readme.rst, roles/addons/grafana/tasks/main.yml, roles/addons/grafana/vars/RedHat.yml
I was reading #330 and thought it's a shame to install and start the service by hand. :stuck_out_tongue_closed_eyes: 
This is a basic role that add the grafana service to the appropriate firewall zone, install the RPM and start the service. No rocket science.
Tested on CentOS 8.2, management1, with prometheus running on management2.
=> feat: new addon role to install grafana

resources/documentation/learn_ansible.rst
Removed 'my_ship' from 'destination' in html example template.
=> Fix: documentation - remove old syntax

roles/addons/slurm/readme.rst, roles/addons/slurm/tasks/main.yml, roles/addons/slurm/templates/slurm.conf.j2, roles/addons/slurm/vars/RedHat.yml, roles/addons/slurm/vars/Ubuntu.yml
List mandatory and optional variables in the readme.
See #333.
Also fix the path to cgroup.conf (use slurm_home_path) and tests in
Jinja2 template.
=> fix: document variables in role slurm

roles/addons/prometheus_client/tasks/main.yml, roles/addons/prometheus_server/files/alertmanager.xml, roles/addons/prometheus_server/handlers/main.yml, roles/addons/prometheus_server/tasks/main.yml
* add firewall to prometheus_server role
* add firewall to prometheus_client role
* add alertmanager port to firewall
* remove node_exporter port, replace ports by services
* add alertmanager service file
* change "service" to "port" in firewalld task
* replace /usr/lib/firewalld by /etc/firewalld in prometheus_server
* Remove blank character at EOL
* reload firewalld after adding a service
* fix duplicated when condition in prometheus_client role
Co-authored-by: Bruno Travouillon <devel@travouillon.fr>
(cherry picked from commit cc6a3f576699cb40f4a0a3f3e65ab49322343077)
=> backport: add firewall to prometheus  (#361)

roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml
The role repositories_client can change the default repository
configuration for CentOS with the ini_file module. This should only
apply if the file already exists. If it does not exist, do not create the
file.
ini_file defaults to `create: yes`, which makes the CI fail because the `mode` is not defined.
=> fix: don't create ini file if absent

roles/addons/diskless/files/disklessset.py
The image folder is created at the begining of the image creation
process while the image_metadata.yml file is created at the end. When
the image creation process fails, the directory exists but the metadata
file does not exist.
Check if the metadata file exists before read. Otherwise, print a
warning to inform the user the image is incomplete.
See: #296
=> fix: check if diskless image_metadata.yml exists

roles/addons/diskless/files/disklessset.py, roles/addons/diskless/readme.rst
* adding example and clarification
* miscalculation
* precision
* clarification readme
* Update readme.rst
* indentation
* deletion of size indications
* adding example for option 4
* bad unit
* Update readme.rst
* clarification
* clarification, correction, change command
* Update readme.rst
* Update roles/addons/diskless/readme.rst
Co-authored-by: Bruno Travouillon <devel@travouillon.fr>
* Update readme.rst
a blank line is missing => ok
5G is more user-friendly. => ok
* Update readme.rst
Co-authored-by: Bruno Travouillon <devel@travouillon.fr>
(cherry picked from commit 14c445719e871b5fbb8d7908fdad742e47063a18)
=> backport: adding example and clarification (#357)

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/repositories.yml, resources/examples/simple_cluster/inventory/group_vars/all/general_settings/repositories.yml, roles/core/repositories_client/readme.rst
The variable remove_distro_repositories does not exist anymore.
=> fix: delete old variable from inventory

roles/addons/report/templates/equipment_profiles.html.j2, roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
If not defined, it will default to 'standard'.
=> fix: ensure ep_ipxe_embed is defined before use

CHANGELOG.md, resources/documentation/deploy_bluebanquise.rst
Based on user feedback in the field, some instruction were not clear or
even wrong.
(cherry picked from commit 3d0c8f62878038ff3e26bf938a61a5034c286032)
=> doc: rephrase and fix the CHANGELOG and doc

roles/core/pxe_stack/templates/menu.ipxe.j2
Add the grub2 shell entry in the menu.
Was present in the rpm, but missing here.
Related to https://github.com/bluebanquise/bluebanquise/issues/360
=> Fix: pxe_stack - add grub2 shell in menu.ipxe

roles/addons/diskless/tasks/main.yml
=> fix: ensure selinux type is correct on diskless directories

roles/core/hosts_file/templates/hosts.j2
Prevent many empty lines when hosts are defined in the inventory, but without network_interfaces.
=> Fix: hosts_file - Prevent massive empty lines generation

roles/addons/diskless/files/disklessset.py
Hello,
When a node boots on a customized diskless image, its interfaces names aren't renamed: 
```
systemd-udevd[4443]: Error changing net interface name 'eth0' to 'enp61s0f0': Device or resource busy
could not rename interface '2' from 'eth0' to 'enp61s0f0': Device or resource busy
```
And, diskless nodes got two "No DHCPOFFERS received" during les 10 minutes afterboot.
```
Oct  5 17:56:31 pm5-nod64 dhclient[4867]: No DHCPOFFERS received.
Oct  5 18:01:19 pm5-nod64 dhclient[4867]: No DHCPOFFERS received.
```
It missing two modules dracut in dracut CLI generator.
Regards
=> [diskless] customized image boots with incorrect interfaces names

roles/addons/diskless/readme.rst, roles/core/time/tasks/main.yml
Hello,
The timezone module isn't designed to work in a chroot environment, so we have to add the identify tag in task role.
```
RUNNING HANDLER [log_client : Restart rsyslog services] 
*************************************************************
Thursday 01 October 2020 02:53:57 +0200 (0:00:00.338) 0:00:12.768 ******
ok: [/var/tmp/diskless/workdir/dkl_last_kernel_custom/mnt] => (item=rsyslog)
[WARNING]: Target is a chroot or systemd is offline. This can lead to false positives or prevent the init system tools from working.
TASK [log_client : Manage services state] 
*******************************************
```
Regards
=> [diskless] The time role isn't functional for a custom diskless image

.github/workflows/static_analysis.yml, CHANGELOG.md, resources/packaging/bluebanquise.spec, roles/addons/Lmod/tasks/main.yml, roles/addons/Lmod/templates/modules_extra_path.sh.j2, roles/addons/Lmod/vars/RedHat.yml, roles/addons/clone/tasks/main.yml, roles/addons/lmod/readme.rst, roles/addons/lmod/tasks/main.yml, roles/addons/lmod/templates/modules_extra_path.sh.j2, roles/addons/lmod/vars/RedHat.yml, roles/addons/openldap_server/tasks/main.yml, roles/addons/prometheus_server/tasks/main.yml, roles/addons/sssd/tasks/main.yml, roles/core/ssh_master/molecule/default/prepare.yml
We did a great job over the year to improve the quality of the code. It's now time to finish the work and enable the ansible linter on the whole project tree in the CI.
List of remaining errors:
- 106  Role name {} does not match ``^[a-z][a-z0-9_]+$`` pattern
- 201  Trailing whitespace
- 202  Octal file permissions must contain leading zero or be a string
- 208  File permissions not mentioned
- 301  Commands should not change things if nothing needs doing
List of changes to make the linter happy 😁 :
- Remove trailing whitespaces
- Set mode for file permissions: use the default values (0755 for dir, 0644 for files)
- Update the check of /etc/sysconfig/authconfig in role sssd
- Rename role Lmod to lmod ([Role names are now limited to contain only lowercase alphanumeric characters, plus _ …
=> ci: run ansible-lint on whole project tree

roles/core/nic/readme.rst
Fix readme, since having slave NIC first in the list break the rules defined in the CHANGELOG.md:
1. The main resolution network of hosts is the value of the network parameter of the first item of the list (e.g., c001 will be on the same line than c001-ice1-1 in the hosts file).
2. First management network related item in the list will be the ansible main ssh target interface (from ssh_master role), and also the main management network interface for the client (services_ip to target on client side).
=> Fix: core/nic - Update readme

roles/core/time/molecule/default/verify.yml
Previous test was unreliable: when summer time is over, tz = CET.
Because we define the timezone to be 'Europe/Paris', check the
host configuration is updated to reflect that change. For this, check
/etc/localtime is a symlink to /usr/share/zoneinfo/Europe/Paris.
Tests are failing since Sunday when the time changed in Europe/Paris: https://github.com/bluebanquise/bluebanquise/runs/1310835559
=> ci: test timezone is 'Europe/Paris'

roles/core/dns_server/templates/forward.j2
BMC alias are missing in the forward dns file.
=> Fix: core/dns_server - Missing bmc alias

roles/advanced-core/advanced_dns_server/templates/forward.j2
Missing bmc alias in advanced dns server.
=> Fix: adv_core/adv_dns_server

.github/TEST_MATRIX.md, .github/workflows/molecule-actions-advanced_core-advanced_dns_server.yml, roles/advanced-core/advanced_dns_server/molecule/default/converge.yml
We forgot the CI during the move of role core/dns_server to advanced-core/advanced_dns_server...
=> ci: add advanced_dns_server molecule test

roles/core/repositories_client/molecule/default/molecule.yml, roles/core/repositories_client/molecule/default/prepare.yml, roles/core/repositories_client/molecule/default/verify.yml, roles/core/repositories_client/readme.rst, roles/core/repositories_client/tasks/centos_7.yml, roles/core/repositories_client/tasks/centos_8.yml, roles/core/repositories_client/tasks/opensuse_leap_15.yml, roles/core/repositories_client/tasks/redhat_7.yml, roles/core/repositories_client/tasks/redhat_8.yml, roles/core/repositories_client/tasks/ubuntu_18.yml, roles/core/repositories_client/vars/main.yml
It is possible to ensure a repository does not exist with:
```
repositories:
- { name: 'repo_to_delete', state: 'absent'}
```
See #455.
=> feat: add parameter state to repositories_client

.github/TEST_MATRIX.md, .github/workflows/molecule-actions-advanced-core-advanced_dhcp_server.yml, roles/advanced-core/advanced_dhcp_server/.yamllint, roles/advanced-core/advanced_dhcp_server/molecule/default/INSTALL.rst, roles/advanced-core/advanced_dhcp_server/molecule/default/converge.yml, roles/advanced-core/advanced_dhcp_server/molecule/default/molecule.yml, roles/advanced-core/advanced_dhcp_server/molecule/default/prepare.yml, roles/advanced-core/advanced_dhcp_server/molecule/default/verify.yml
Molecule tests for advanced_dhcp_server role.
- Test shared networks feature in dhcp
- Check compute with mac address
- Check (opt61 and opt82) in dhcp configuration.
- Check dhcp syntax with `dhcpd -t -cf /etc/dhcp/dhcpd.conf`
- Check dhcpd service is enabled
=> Adding molecule unitary tests for advanced_dhcp_server role

roles/core/display_tuning/files/screenrc
Removing all dynamic elements.
Reason: this prevent scrolling, which is pretty annoying. I did not see that part when doing this role.
=> Fix: core/display_tuning - Remove dynamic elements

.github/TEST_MATRIX.md, .github/workflows/molecule-actions-core-repositories_server.yml, .github/workflows/molecule-actions-core-ssh_slave.yml, roles/core/repositories_server/.yamllint, roles/core/repositories_server/molecule/default/INSTALL.rst, roles/core/repositories_server/molecule/default/converge.yml, roles/core/repositories_server/molecule/default/molecule.yml, roles/core/repositories_server/molecule/default/prepare.yml, roles/core/repositories_server/molecule/default/verify.yml, roles/core/ssh_slave/.yamllint, roles/core/ssh_slave/molecule/default/INSTALL.rst, roles/core/ssh_slave/molecule/default/converge.yml, roles/core/ssh_slave/molecule/default/molecule.yml, roles/core/ssh_slave/molecule/default/verify.yml
Adding molecule test for remaining core roles:
- repositories_server 
- ssh_slave roles
The following roles cannot be tested in containers, due to limits of docker (`error: Device or resource busy`)
These roles will be tested in a full virtualized environment with kitchen.
- hosts_file
- set_hostname
=> Add molecule tests for repositories_server and ssh_slave roles

roles/addons/nhc/defaults/main.yml, roles/addons/nhc/readme.rst, roles/addons/nhc/tasks/main.yml, roles/addons/nhc/templates/nhc.conf.j2, roles/addons/nhc/templates/nhc_custom_file.j2, roles/addons/nhc/vars/main.yml
This change allows to define the name and content of each custom files
one want to install in /etc/nhc/ in the user inventory. This helps to
keep all the configuration in the inventory instead of splitting some
values in the inventory for templates and in the role for files.
=> feat: template custom NHC files from the inventory

roles/addons/diskless/readme.rst
Please see #495.
This fix is to document how to use the customization playbook to manage the firewall in diskless images.
Notice that adding `ep_firewall` variable is not needed as long as `image_equipment_profile` is provided in the playbook.
The approach has been tested on a customized livenet image, firewalld service is disabled after boot.
Playbook used:
```
- name: Computes diskless playbook
hosts: /var/tmp/diskless/workdir/{{ diskless_image }}/mnt
connection: chroot
vars:
j2_current_iceberg: iceberg1
j2_node_main_network: ice1-1
start_service: false
image_equipment_profile: equipment_typeC
pre_tasks:
- name: Add current host to defined equipment_profile
add_host:
hostname: "{{ inventory_hostname }}"
groups: "{{ image_equipment_profile }}"
roles:
- firewall
```
Playbook result:
``` …
```
=> Fix: Documentation on firewalld service in diskless images (#495)

roles/core/nic/readme.rst, roles/core/nic/templates/ifcfg.j2, roles/core/nic/vars/main.yml
If you want to assign a firewalld zone to a network interface, define
the zone in the network linked to the interface. The zone name will be
added to the ZONE parameter of the ifcfg file.
As for other changes made by the nic role, the network service needs
to be restarted for changes to take effect.
=> feat: add configuration of firewall zone to nic

roles/core/conman/tasks/main.yml, roles/core/log_server/tasks/main.yml
Remove mode: 0750 for file tasks where recurse: yes.
All the files in the directory will inherit this mode, which is wrong.
This mode was added in commit d70ad62 to resolve an error reported by
ansible-lint. Use #noqa 208 instead to skip the qa for this task, we can
rely on default mode set during the installation of the RPM.
=> fix: skip ansible-lint rule 208 when recurse: yes

.github/TEST_MATRIX.md, .github/workflows/molecule-actions-core-set_hostname.yml, roles/core/set_hostname/molecule/default/converge.yml, roles/core/set_hostname/molecule/default/molecule.yml, roles/core/set_hostname/molecule/default/verify.yml
The purpose of this test is to ensure the role can run, even if it's a single task role today.
The test does not change the hostname of the instance because it is not possible to change the hostname with hostnamectl in a running container (Could not set property: Failed to set static hostname: Device or resource busy).
Molecule, with the docker driver, will create a container with hostname `instance`, then will use this name as `inventory_hostname`. The role uses this variable in the task, which should not change the hostname. In the verify step, molecule gathers the facts and check that `ansible_hostname` is `instance`.
=> ci: setup molecule for set_hostname

roles/addons/nic_nmcli/readme.rst, roles/addons/nic_nmcli/tasks/main.yml, roles/addons/nic_nmcli/vars/main.yml
It is a feat, branch name mention fix, this is a mistake.
* Update routes to a much simpler format.
* Add Firewall zone.
Note that routes format change. Previous format was introduced recently, and should still not be used by any one, but in case of.
=> Feat: addons/nic_nmcli - Update routes, add zones

.github/workflows/molecule-actions-core-repositories_client.yml, roles/core/ssh_master/molecule/default/molecule.yml
I'm currently testing the GitHub Actions with the image **ubuntu-20.04** to prepare the coming change of **ubuntu-latest**: *Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816*.
I identified some issues with the CI which I'm trying to fix in this PR. So far, the changes below are not related to ubuntu-20.04, but to some changes in GitHub Actions and molecule since the last run of the test. We could identify this kind of changes earlier by running each test at least once a week.
The set-env command is disabled in GitHub Actions due to CVE-2020-15228.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
molecule 3.2.0 was released a couple of days ago. The current …
=> ci: fix some issues with GitHub Actions

CHANGELOG.md, roles/core/pxe_stack/files/osdeploy/centos_7.ipxe, roles/core/pxe_stack/files/osdeploy/centos_8.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe, roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe, roles/core/pxe_stack/templates/kickstart.cfg.j2
Prevent issues when using the curl feedback at the end of kickstart.
Had issues when upgrading to RHEL 8.3. Solves this, and no more dependencies to distribution.
=> Fix: pxe_stack - Forcing hostname via kernel command

resources/documentation/learn_ansible.rst
Previous URL now gives a 404. The content at the new URL is slightly
different but roughly similar.
=> Fix ansible modules documentation URL

CHANGELOG.md, roles/addons/diskless/files/livenet_module.py
This PR relates to the following issues regarding livenet images in the diskless role: #523 #521 #524
- For #523, using `cp -a` instead of `cp -r` will keep the setuid flag for /usr/bin/sudo.
- For #521, asking disklessset to disable SELinux would put `selinux=False` in the kernel command line, which would not disable SELinux during boot. The proposed fix will correctly write `selinux=0` in the kernel command line.
- For #524, the `self.MOUNT_DIRECTORY` variable is created with a `/` at the end and used in many places in the code. The proposed fix will keep the variable as-is but remove the `/` when writing the host file.
=> Fix issues found when booting a diskless livenet image 

.github/workflows/molecule-actions-core-time.yml, .github/workflows/static_analysis.yml, roles/addons/nic_nmcli/tasks/main.yml, roles/addons/powerman/tasks/main.yml, roles/addons/prometheus_server/tasks/main.yml, roles/advanced-core/advanced_dns_server/tasks/main.yml, roles/core/conman/tasks/main.yml, roles/core/dhcp_server/tasks/main.yml, roles/core/dns_server/tasks/main.yml, roles/core/firewall/tasks/RedHat.yml, roles/core/log_client/tasks/main.yml, roles/core/log_server/tasks/main.yml, roles/core/nfs_server/tasks/main.yml, roles/core/pxe_stack/tasks/main.yml, roles/core/time/tasks/main.yml, tox.ini
1) Update tox file:
- The stack requires >= 2.9.13.
- Don't test with ansible 2.8 anymore.
- Run tests with ansible 2.9, 2.10 and 3.
2) Revert ebfa28f since ansible-base 2.10.7 is released (resolve `firewalld` to the correct FQCN).
3) Pin molecule CI for role time to Ubuntu 18.04 runner.
4) Ansible-lint 5.0.3 enforce rule unnamed-task for Task/Handler: meta.
Fix the failures below with ansible-lint:
```
unnamed-task: All tasks should be named
roles/addons/nic_nmcli/tasks/main.yml:120 Task/Handler: meta  flush_handlers
unnamed-task: All tasks should be named
roles/addons/powerman/tasks/main.yml:22 Task/Handler: meta  flush_handlers
unnamed-task: All tasks should be named
roles/addons/prometheus_server/tasks/main.yml:47 Task/Handler: meta  flush_handlers
role-name: Role name advanced-core …
```
=> ci: fix ansible versions and failing tests

roles/core/clustershell/tasks/main.yml, roles/core/lvm/tasks/main.yml, roles/core/powerman/tasks/main.yml
Was mistakenly replaced by always during move of the roles from addons
to core.
=> fix: use tag package for package tasks

CHANGELOG.md, roles/core/time/molecule/default/converge.yml, roles/core/time/molecule/default/molecule.yml, roles/core/time/molecule/default/verify.yml, roles/core/time/readme.rst, roles/core/time/tasks/main.yml, roles/core/time/vars/main.yml
Add a new inventory variable time_chronyd_options to configure the value
of OPTIONS in /etc/sysconfig/chronyd. For full list of options, see
chronyd(8).
With this change, it is now possible to disable the control of the
system clock when running chronyd in containers, which is especially
useful when running CI in rootless containers.
Test this new feature with all previously defined hosts in molecule.
Create a new host 'client-no-start' which does not change the
/etc/sysconfig/chronyd and does not start the chronyd service.
Bump role time's version to 1.1.0 and update changelogs.
=> feat: set sysconfig OPTIONS for chronyd

roles/core/time/tasks/main.yml
Hello,
This is not a real bug but mostly cosmetic.
In the generation of the /etc/chrony.conf file, in the case of a chrony-server.conf file, you do not change the title of the display. As I had to debug this part I was "disturbed" with this not being modified on the fly.
I believe it should be easy to validate.
=> time: just a cosmetic for the generation of chrony conf

roles/core/kernel_config/tasks/main.yml
Crash if variable is None. Small fix to prevent that.
=> Fix: kernel_config - Prevent crash if variable is None

roles/core/nic_nmcli/readme.rst, roles/core/nic_nmcli/tasks/main.yml, roles/core/nic_nmcli/vars/main.yml
Rewrite the role logic.
One line jinja was hard to read or debug, and did not covered all needed aspects.
Using dedicated variables that contains multi lines jinja code allows greater capabilities, while having a readable code.
=> Feat: nic_nmcli - Improve role capabilities

CHANGELOG.md, roles/core/time/readme.rst, roles/core/time/templates/chrony.conf.j2
Hello,
Here is a little patch I had to setup. Maybe this is not the best way to write it but it works. In my case, I had to add some routed networks to my chrony-server which were allowed to get access to the time service.
Before this patch, the networks were all extracted from the NIC interfaces but this was not enough.
This solves this issue: https://github.com/bluebanquise/bluebanquise/issues/553
=> time: add feature to have additional networks allowed

CHANGELOG.md, roles/advanced_core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Hello,
In the extract of ```dhcpd.subnet.conf.j2``` in a configuration containing more than 2000 nodes, the previous version lead to a file where there was a line containing the number of nodes spaces. In this case DHCP does not want to start!
The fix only consists in removing all white spaces between comments and loop/tests sections.
I have also added a small fix removing a double blank line added while running the extract:
```diff
@@ -16,7 +16,7 @@
###############################################################################}
{% macro write_host(macro_host, macro_nic, macro_filename) %}
-{% if macro_nic.dhcp_pattern is defined and macro_nic.dhcp_pattern is not none %}
+{%- if macro_nic.dhcp_pattern is defined and macro_nic.dhcp_pattern is not none %}
{{ …
```
=> advanced_dhcp_server: fix issue with added spaces linked to spaces in comments

CHANGELOG.md, roles/core/diskless/readme.rst
When customizing and image with disklessset tool, firewalld fails to start in the chroot environment.
=> Docs: diskless - firewall doesn't work in chroot

CHANGELOG.md
Backport was registered against v1.5 instead of 1.4.
=> Fix: changelog - change in wrong section

CHANGELOG.md, roles/addons/diskless/files/livenet_module.py
Hotfix: Somehow in the backport a string was treated as a list. This is a fatal error.
=> Fix: disklessset - string used as a list

CHANGELOG.md, roles/core/conman/tasks/main.yml
This is  a backport of #551 for 1.4.1 release.
=> Backport/1.4.1/551 (conman: add conman user the authorization to write into /var/run/conman)

CHANGELOG.md, roles/core/diskless/tasks/main.yml
The path for diskless files was incorrect, for example:
```
- /lib/{{ diskless_python_version }}/site-packages/diskless
```
with diskless_python_version being "3.6" (RedHat 8) or "3.9" (RedHat 9). The path should be "python3.6" or "python3.9":
```
- /lib/python{{ diskless_python_version }}/site-packages/diskless
```
=> Fix: diskless - Correct python path

CHANGELOG.md, roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Backport PR #561 that fixes trailing spaces in dhcp server config to 1.4.2.
=> Backport: 1.4.2/551 advanced_dhcp_server trailing spaces fix

CHANGELOG.md, roles/core/pxe_stack/tasks/main.yml
In the upgrade from BB v1.4 to v1.5, some files became links. Without the "force" attribute, Ansible refuses to do the replacement.
```
TASK [pxe_stack : file █ Generate links for all supported OS] ****************************************************************************************************************************************
Thursday 05 August 2021  16:10:34 -0300 (0:00:27.997)       0:01:47.544 *******
skipping: [mngt0-1] => (item=[{'major': 7, 'distributions': ['redhat', 'centos']}, 'redhat'])
failed: [mngt0-1] (item=[{'major': 7, 'distributions': ['redhat', 'centos']}, 'centos']) => changed=false
ansible_loop_var: item
gid: 48
group: apache
item:
- distributions:
- redhat
- centos
major: 7
- centos
mode: '0644'
msg: refusing to convert from file to symlink for …
```
=> Fix: pxe_stack - Force substitution from file to symlink

roles/core/dns_server/molecule/default/verify.yml, roles/core/dns_server/readme.rst, roles/core/dns_server/tasks/main.yml, roles/core/dns_server/templates/named.conf.j2, roles/core/dns_server/templates/reverse.j2, roles/core/dns_server/vars/main.yml
Changed the generation of the reverse zone file to instead be one file per network that is defined to be in DNS. The network prefix is used to generate the corresponding `in-addr.arpa` entries.
Reverse zones are named: `{{ network }}.rr.zone` and SOA files are similarly named `{{ network }}.rr.soa`
=> Re-worked reverse zone file generation for dns_role to fix issue #614

tox.ini
I think we should restrain python 2.7 to Ansible 2.9 as Rhel7 is the only distrib we are supporting with python 2.7, and it is based on Ansible 2.9.
I see always too much issues with more recent Ansible, event if it should be supported by Ansible team.
=> Fix: Tox - Update envlist

CHANGELOG.md, roles/core/nic_nmcli/readme.rst, roles/core/nic_nmcli/tasks/main.yml, roles/core/nic_nmcli/vars/main.yml
The optional parameter of nic_nmcli role does not work, the role fails with this error message:
```
...
TASK [nic_nmcli : shell █ Force apply nic settings] **********************************************************************
Tuesday 11 January 2022 16:31:38 +0100 (0:00:01.108) 0:00:08.516 *******
fatal: [management1]: FAILED! =>
msg: '''nic_nmcli_apply'' is undefined
```
This PR adds the missing variable definition, and the role works as expected.
=> Fix: nic_nmcli - add missing register of nic_nmcli_apply variable

CHANGELOG.md, roles/core/pxe_stack/tasks/client_os/RedHat.yml, roles/core/pxe_stack/tasks/client_os/Ubuntu.yml, roles/core/pxe_stack/vars/main.yml
Had the same problem as described in [#587](https://github.com/bluebanquise/bluebanquise/pull/587).
This time from bb-1.4 to 1.5.
Somehow the fix was removed during the update.
=> Fix: pxe_stack force substitution from file to symlink

resources/documentation/conf.py, roles/core/dns_server/defaults/main.yml, roles/core/dns_server/readme.rst, roles/core/dns_server/tasks/main.yml, roles/core/dns_server/tasks/reverse.yml, roles/core/dns_server/templates/named.conf.j2, roles/core/dns_server/templates/reverse.j2, roles/core/dns_server/vars/main.yml
This mod changes the `dns_server` role so that reverse zone files are created in the form `xxx.yyy.zzz.rr.zone` for every host/BMC IP that matches.
If this is acceptable, the same mods can be made to to the `advanced_dns_server` role.
=> Fix for issue #682 in dns_server role

CHANGELOG.md, roles/advanced_core/advanced_dhcp_server/readme.rst, roles/advanced_core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2, roles/advanced_core/advanced_dhcp_server/vars/main.yml
Enables the usage of a time_ip list same way as is done with dns_ip.
Thanks to N. Capit.
=> Feat: advanced_dhcp_server - allow time_ip list

roles/core/pxe_stack/readme.rst, roles/core/pxe_stack/templates/Suse/autoyast.xml.j2, roles/core/pxe_stack/vars/main.yml, roles/core/repositories_client/readme.rst, roles/core/repositories_client/tasks/Suse/main.yml, roles/core/repositories_client/vars/main.yml
**pxe_stack**
- Handle installation of `sudo` package if sudo usage has been chosen
- Only set product and add on repositories if using SLES - not applicable to OpenSUSE
**repositories_client**
- Update SUSE sub task to better handle a repository definition where a dictionary is use. For example:
```
repositories:
- name: oss
disable_gpg_check: true
```
With the current code, this definition causes an error. With my modification this is no longer the case.
=> OpenSUSE / SLES fixes

CHANGELOG.md, roles/core/dhcp_server/defaults/main.yml, roles/core/dhcp_server/readme.rst, roles/core/dhcp_server/templates/dhcpd.conf.j2
Allows to switch between ipxe roms with default simple dhcp server. Some hardware need snponly roms, and you may not want to use advanced dhcp server.
=> Feat: dhcp_server - Add capability to choose ipxe ROM

roles/advanced_core/advanced_dhcp_server/readme.rst, roles/advanced_core/advanced_dhcp_server/tasks/Suse/firewall.yml, roles/advanced_core/advanced_dhcp_server/tasks/Suse/main.yml, roles/advanced_core/advanced_dhcp_server/tasks/main.yml, roles/advanced_core/advanced_dhcp_server/templates/Suse/sysconfig.j2, roles/advanced_core/advanced_dhcp_server/templates/dhcpd.conf.j2, roles/advanced_core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2, roles/advanced_core/advanced_dhcp_server/vars/RedHat_7.yml, roles/advanced_core/advanced_dhcp_server/vars/Suse.yml, roles/advanced_core/advanced_dhcp_server/vars/Suse_12.yml, roles/advanced_core/advanced_dhcp_server/vars/Ubuntu.yml, roles/advanced_core/advanced_dhcp_server/vars/main.yml
Updated the `advanced_dhcp_server` role to work with OpenSUSE/SLES for issue #696
=> Updated advanced_dhcp_server role for OpenSUSE/SLES for issue #696

.github/workflows/global_centos_7.yml, .github/workflows/global_opensuseleap_15.yml, .github/workflows/global_rocky_8.yml, .github/workflows/global_ubuntu_20.04.yml, CHANGELOG.md, roles/advanced_core/advanced_dhcp_server/vars/Suse.yml, roles/advanced_core/advanced_dns_server/vars/Ubuntu.yml, roles/core/dhcp_server/vars/Suse.yml, roles/core/dhcp_server/vars/Ubuntu.yml, roles/core/dns_server/vars/Ubuntu.yml
Fix packages installation that should no more occur since all deps comes from pip (requirements.txt).
This is last PR before 1.6 release as no more blocking bug were reported.
=> Fix: all - Remove netaddr packages in roles

roles/core/pxe_stack/tasks/client_os/Ubuntu.yml
Hi!
This is only while creating the Ubuntu cloud-init empty "meta-data" file.  The Ansible module "file" 'touch'es the "meta-data" file every time the role is played (modifying the access time of the "meta-data" file).  Suggesting to replace with the Ansible module "copy" with an empty content.
Thanks!
=> Improve idempotency of role pxe_stack

roles/core/repositories_client/tasks/main.yml
Hi,
To allow subsequent roles to install packages.
Thanks!
=> Fix: flush handlers at the end of role repositories_client

roles/core/dns_server/readme.rst, roles/core/dns_server/templates/named.conf.j2, roles/core/dns_server/vars/main.yml
Hi!
For network interfaces which are bond slaves, the `network` parameter may not be defined (since it is defined in the bond master interface), which leads the `dns_server` role to fail.
Suggesting to check whether `network` is defined.  Might be useful to additionally check `if network is not none`?
Thanks!
=> fix: in role dns_server, check if network is defined

roles/core/pxe_stack/tasks/client_os/DGX.yml, roles/core/pxe_stack/templates/RedHat/kickstart.cfg.j2, roles/core/pxe_stack/templates/Suse/autoyast.xml.j2, roles/core/pxe_stack/templates/Suse/autoyast_sles12.xml.j2, roles/core/pxe_stack/templates/Ubuntu/preseed.cfg.j2, roles/core/pxe_stack/templates/Ubuntu/user-data.j2
Hi!
Some kernel options may contain dots (like `modprobe.blacklist=`, `rd.driver.blacklist=`, `pciehp.pciehp_debug=`, etc.), so we can't evaluate those options as shell variables when preparing the bootswitch.
The idea here is to only retrieve the necessary kernel cmd line options to evaluate them as shell vars, before curl'ing the bootswitch.
Thanks!
=> fix: to prepare bootswitch, retrieve from kernel cmd line only the necessary variables

roles/core/pxe_stack/tasks/client_os/DGX.yml
Hi!
When tweaking the DGX-OS curtin file to configure all network interfaces in DHCP after 1st reboot in the so-called "late commands", fix improper use of single & double quotes (don't use single quotes for both inner quotes and outer quotes).
Here: using single quotes as outer, and double quotes as inner because when need shell variable expansion.
Also simplifying the code a little.
Thanks!
=> fix: pxe_stack role — rationalize single and double quote nested usage

bootstrap.sh
fix a wrong variable call for ${REPO_PATH} on the copy iso step for el8 platform.
=> Fix bootstrap.sh iso copy [rhel-like]

roles/core/powerman/tasks/main.yml
Fix issue #731
Filter package is no more needed since file is embed into role at https://github.com/bluebanquise/bluebanquise/blob/master/roles/core/powerman/filter_plugins/nodeset.py
=> Fix: issue 731

roles/core/diskless/vars/RedHat_8.yml
The real files provided by the tool on the latest version is under /usr/lib:  ( at least for the el8 version)
$ rpm -qa bluebanquise-disklessset
bluebanquise-disklessset-1.3.7-1.el8.noarch
$ rpm -ql bluebanquise-disklessset
/usr/bin/bluebanquise-disklessset
/usr/bin/disklessset
/usr/lib/python3.6/site-packages/diskless/__pycache__
/usr/lib/python3.6/site-packages/diskless/__pycache__/image_manager.cpython-36.opt-1.pyc
/usr/lib/python3.6/site-packages/diskless/__pycache__/image_manager.cpython-36.pyc
/usr/lib/python3.6/site-packages/diskless/__pycache__/kernel_manager.cpython-36.opt-1.pyc
/usr/lib/python3.6/site-packages/diskless/__pycache__/kernel_manager.cpython-36.pyc
/usr/lib/python3.6/site-packages/diskless/__pycache__/utils.cpython-36.opt-1.pyc …
=> Update the "diskless_usr_lib_dir" var to /usr/lib

bootstrap.sh, requirements.txt
To solve this:
Collecting ansible>=4.10.0 (from -r requirements.txt (line 1))
Collecting netaddr>=0.7.19 (from -r requirements.txt (line 2))
Collecting clustershell (from -r requirements.txt (line 3))
Collecting jmespath>=0.9.5 (from -r requirements.txt (line 4))
Collecting Cython (from -r requirements.txt (line 6))
Collecting ansible-core~=2.11.7 (from ansible>=4.10.0->-r requirements.txt (line 1))
Collecting importlib-resources; python_version < "3.7" (from netaddr>=0.7.19->-r requirements.txt (line 2))
Collecting PyYAML (from clustershell->-r requirements.txt (line 3))
Collecting jinja2 (from ansible-core~=2.11.7->ansible>=4.10.0->-r requirements.txt (line 1))
Collecting cryptography (from ansible-core~=2.11.7->ansible>=4.10.0->-r requirements.txt (line 1))
Complete output from command …
=> added pip updating for offline bootstrap

collections/infrastructure/plugins/modules/networkd.py, collections/infrastructure/roles/nic/tasks/Ubuntu/main.yml
Add MTUBytes in [Link] section if mtu is provided for an interface.
Test input:
```
- interface: eth_ips_mtu
ip4: 10.10.0.1/16,10.10.0.2/16  # Multiple ip possible
gw4: 10.10.0.254
mtu: 8000
```
Correct output: 
```
[Match]
Name=eth_ips_mtu
[Network]
DNS=10.10.0.1
[Address]
Address=10.10.0.1/16
Address=10.10.0.2/16
[Route]
Gateway=10.10.0.254
[Link]
MTUBytes=8000
```
=> feat: nic - Add support for MTU in Ubuntu

collections/infrastructure/plugins/modules/networkd.py, collections/infrastructure/roles/nic/tasks/Ubuntu/main.yml
Adding options for bond interfaces on Ubuntu + systemd-networkd.
Checking that the input does not contain any "s", or "ms" for time intervals, since we are following nmcli convention and it assumes a number representing milliseconds.
Example input:
```
- interface: bond0
ip4: 10.10.0.1
type: bond
mode: 802.3ad
miimon: 900
```
Output for bond0.netdev:
```
[NetDev]
Name=bond0
Kind=bond
[Bond]
Mode=802.3ad
MIIMonitorSec=900ms
```
Note: had to look around for the acceptance of "900ms", since it is not documented. See here https://bugs.launchpad.net/netplan/+bug/1745597
=> Feat nic bond options

collections/infrastructure/plugins/modules/networkd.py
Multiple IPs were being rendered like this:
```
[Match]
Name=eth_ips_mtu
[Network]
DNS=10.10.0.1
[Address]
Address=10.10.0.1/16
Address=10.10.0.2/16
[Route]
Gateway=10.10.0.254
```
systemd-networkd does not like that, fixing so that each address gets its own [Address] field:
```
[Match]
Name=eth_ips_mtu
[Network]
DNS=10.10.0.1
[Address]
Address=10.10.0.1/16
[Address]
Address=10.10.0.2/16
[Route]
Gateway=10.10.0.254
```
=> fix: nic - Create one [Address] section for each IP address in Ubuntu

roles/core/dns_server/templates/override.j2
Fix override configuration file to use same zone as cluster, otherwise de domain will not be searched correctly
=> Fix override.j2

CHANGELOG.md, collections/infrastructure/roles/repositories/readme.rst, collections/infrastructure/roles/repositories/tasks/Ubuntu/main.yml, collections/infrastructure/roles/repositories/vars/main.yml
Support gpgkey/gpgcheck options for Ubuntu in repositories_client role.
Given the input:
```
repositories:
- name: repo-no-gpg
- name: repo-with-gpg
gpgcheck: 1
gpgkey: /usr/share/keyrings/gpgkey-12345678-keyring.gpg
distribution: jammy main
```
The following output is produced at /etc/apt/sources.list.d 
```
deb [trusted=yes] http://10.10.0.1/repositories//ubuntu/20.04/x86_64/repo-no-gpg ./
```  
```
deb [signed-by=/usr/share/keyrings/gpgkey-12345678-keyring.gpg] http://10.10.0.1/repositories//ubuntu/20.04/x86_64/repo-with-gpg jammy main
```
Note: `apt update` command requires the key in `signed-by` option to be present, otherwise the command will fail.
=> feat: repositories_client - Support gpgkey for Ubuntu

resources/legacy/roles/advanced_core/advanced_dhcp_server/tasks/main.yml
Hello,
during the installation of the advanced DHCP role, I encountered this error:
```
TASK [advanced_dhcp_server : file █ Create /etc/dhcp] ***********************************************************************************************************************************************************************************
Monday 30 January 2023  10:04:43 +0100 (0:00:01.636)       0:00:04.166 ********
fatal: [mngt-01]: FAILED! =>
msg: |-
The task includes an option with an undefined variable. The error was: 'dhcp_server_conf_dir' is undefined
The error appears to be in '/root/bluebanquise/roles/advanced_core/advanced_dhcp_server/tasks/main.yml': line 49, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: "file █ Create …
```
=> fix: advanced_dhcp_server : file Create /etc/dhcp

CHANGELOG.md, collections/logging/roles/rsyslog/README.md, collections/logging/roles/rsyslog/templates/rsyslog_logrotate.j2, resources/legacy/roles/core/rsyslog/templates/server.conf.j2
The rule
```
$template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
*.* ?RemoteLogs
```
was present before and was wrongly removed. It allows app messages to be stored at rsyslog subfolder, otherwise they are lost in the log server.
The block
```
if $fromhost-ip == '127.0.0.1' then {
*.info;mail.none;authpriv.none;cron.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
}
```
makes so that in a HA scenario those logs are also …
=> fix: rsyslog - 768 bug rsyslog server not writing locally apps logs not being fowarded

collections/logging/roles/rsyslog/templates/server.conf.j2
In #771, part of the fix was applied in the old "legacy" version of the role instead of the desire new in collections.
=> [Fix] - Apply fix to correct rsyslog role

collections/infrastructure/roles/dns_server/README.md, collections/infrastructure/roles/dns_server/templates/reverse.j2, collections/infrastructure/roles/dns_server/vars/main.yml
Reverse zone definition templates used j2_node_main_resolution_network to select main interface and write short name, but variable `item` is a network address and not a name.
We propose to check against host_j2_node_main_resolution_address prefix address instead
=> infrastructure/dns_server: find correct default resolution network in reverse zone

collections/infrastructure/roles/firewall/README.md, collections/infrastructure/roles/firewall/defaults/main.yml, collections/infrastructure/roles/firewall/tasks/RedHat/main.yml, collections/infrastructure/roles/firewall/vars/main.yml
Firewalld is configured with `AllowZoneDrifting=yes` by default on RedHat systems, which seems to be a security risk.
We propose to enforce configuration to `no` by default (based on an ansible variable to allow configuratbility)
=> infrastructure/firewall: enforce firewalld AllowZoneDrifting

collections/hpc/roles/slurm/README.md, collections/hpc/roles/slurm/tasks/accounting.yml, collections/hpc/roles/slurm/templates/slurm.conf.j2, collections/hpc/roles/slurm/vars/main.yml
When submitters are not the controller node, they need to be able to connect to slurmdbd for commands like sacct.
This PR sets the AccountingStorageHost variable to the controller host name and opens the corresponding port in the firewall.
=> hpc/slurm: allow submitters to contact accounting host

collections/infrastructure/roles/firewall/README.md, collections/infrastructure/roles/firewall/tasks/RedHat/main.yml, collections/infrastructure/roles/firewall/vars/main.yml
For nodes with multiple NICs, firewalld role didn't set each one in its own firewall zone.
=> infrastructure/firewall: ensure nics are in the correct fw zone

collections/hpc/roles/slurm/README.md, collections/hpc/roles/slurm/vars/RedHat_9.yml, collections/hpc/roles/slurm/vars/main.yml
Support for RedHat 9.
Because pkg name changed from `python3-mysql` to `python3-mysqlclient`...
=> hpc/slurm: RH9 packages

collections/infrastructure/roles/clustershell/README.md, collections/infrastructure/roles/clustershell/defaults/main.yml, collections/infrastructure/roles/clustershell/tasks/main.yml, collections/infrastructure/roles/clustershell/vars/main.yml
When used with online bootstrap, this role has to manage configuration files within `~bluebanquise/ansible_venv/etc/clustershell` instead of `/etc/clustershell`.
This PR allows to use `clustershell_prefix_path` to change the default to any desired value.
=> infrastructure/clustershell: add config variable clustershell_prefix_path

roles/core/log_server/readme.rst, roles/core/log_server/templates/rsyslog_logrotate.j2, roles/core/log_server/vars/main.yml
Backport of #PR 787 into stable-1.6. This fixes an erroneous service name in the logrotate config file.
=> stable-1.6 Backport #787 - fix rsyslog service name

collections/infrastructure/roles/dns_server/README.md, collections/infrastructure/roles/dns_server/vars/Ubuntu.yml, collections/infrastructure/roles/dns_server/vars/main.yml, collections/infrastructure/roles/time/README.md, collections/infrastructure/roles/time/vars/Ubuntu.yml, collections/infrastructure/roles/time/vars/main.yml
Issue with using aliases of systemd service names, the alias will stop working if the service is disabled.
Below is how to reproduce the issue, notice that the last two commands fail. This means that roles using the aliases (time_ will also fail. 
```
root@mngt0-1:~# systemctl status chronyd
● chrony.service - chrony, an NTP client/server
Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2023-03-28 14:54:21 CEST; 1h 11min ago
Docs: man:chronyd(8)
man:chronyc(1)
man:chrony.conf(5)
Main PID: 22798 (chronyd)
Tasks: 2 (limit: 9507)
Memory: 1.5M
CGroup: /system.slice/chrony.service
├─22798 /usr/sbin/chronyd -F -1
└─22799 /usr/sbin/chronyd -F -1
Mar 28 14:54:21 mngt0-1 systemd[1]: Starting chrony, an NTP client/server...
Mar …
```
=> Fix ubuntu service names

collections/high_availability/roles/pcs/README.md, collections/high_availability/roles/pcs/tasks/RedHat/firewall.yml
Last PR #807 (support high_availability on Ubuntu) introduced a bug on RHEL due to a typo.
Apologies for the error, I thoroughly tested the Ubuntu support and thought I also tested RHEL, but I was only testing an old version of the role. Now that I updated the tests to the latest version, the issue appeared. I also confirmed that this PR fixes it.
=> high_availability/pcs: Fix service name in RHEL firewall

collections/high_availability/roles/keepalived/README.md, collections/high_availability/roles/keepalived/defaults/main.yml, collections/high_availability/roles/keepalived/handlers/main.yml, collections/high_availability/roles/keepalived/tasks/main.yml, collections/high_availability/roles/keepalived/vars/Rocky_8.yml
high_availability/keepalived seemed to be broken. This is a proposal to fix it.
OS config vars are only provided for Rocky 8. Tell me if I may change that and what to add into the README.
=> high_availability: fix keepalived

bootstrap/configure_environment.sh
Hello,
I suggest a minor fix that adds a dependency to the automatic configuration of the ansible and bluebanquise environment.
patch works on alma 9.2
Best
the error was as follows: 
```
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* bluebanquise.commons:* (dependency of bluebanquise.infrastructure:2.1.2)
```
=> Bootstrap dependencies error

collections/monitoring/roles/prometheus/README.md, collections/monitoring/roles/prometheus/handlers/main.yml, collections/monitoring/roles/prometheus/tasks/server_alertmanager.yml, collections/monitoring/roles/prometheus/tasks/server_ipmi_exporter.yml, collections/monitoring/roles/prometheus/tasks/server_karma.yml, collections/monitoring/roles/prometheus/tasks/server_prometheus.yml, collections/monitoring/roles/prometheus/tasks/server_snmp_exporter.yml, collections/monitoring/roles/prometheus/vars/main.yml
Restart each service managed by the prometheus role when its systemd file changes. This is relevant when the launch parameters change: the services were not being updated automatically with new launch parameters.
Also changed the order of the handlers in handlers/main.yml, the handler for the systemd daemon-reload must go before the service restarts. FYI, the handlers are executed in the order they are defined, not in the order they are listed in the notify statement: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html#handlers
=> Fix prometheus restart services

collections/hpc/roles/nhc/README.md, collections/hpc/roles/nhc/templates/nhc.conf.j2, collections/hpc/roles/nhc/vars/main.yml
Fix bug that was causing to template with iterable and string vars to be rendered wrongly:
Like this for strings:
```
* || check_fs_free /
* || check_fs_free  
* || check_fs_free 1
* || check_fs_free 0
* || check_fs_free %
```
And this for iterable list :
```
* || check_fs_mount_rw ['-f /scratch', '-f /opt/share']
* || check_fs_mount_rw ['-f /scratch', '-f /opt/share']
```
=> Fix nhc.j2 template bug

collections/infrastructure/roles/pxe_stack/templates/nodes_parameters.yml.j2
Nodes parameters should fallback to single iceberg when no multiple icebergs is detected.
=> HOTFIX-5 - Fix missing icebergs patterns

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/README.md, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless, collections/infrastructure/roles/pxe_stack/vars/main.yml
Option "Update a reference image default kernel" in bluebanquise-diskless failed on a dev environment. There are several issues and fixes here to make the option work.
1. Code failed:
```Traceback (most recent call last):
File "./bluebanquise-diskless", line 531, in <module>
ipxe_file.write(file_lines)
TypeError: write() argument must be str, not list 
```
Fix by using "writelines()".
2. Code to update boot.ipxe produces wrong output
```
#!ipxe
echo |
echo | Entering diskless/images/RHEL_9.3-ref/boot.ipxe
echo |
set image-kernel vmlinuz-5.14.0-362.18.1.el9_3.x86_64set image-initramfs initramfs-5.14.0-362.18.1.el9_3.x86_64.img        echo | Now starting nfs image boot. 
```
Fix by adding '\n'
3. Wrong permissions and ownership on copied kernel/initramfs
```
-rw-r--r-- 1 root root 1.2K Feb …
```
=> fix: pxe_stack - fix kernel upgrade option in bluebanquise-diskless

CHANGELOG.md, roles/core/nfs_server/defaults/main.yml, roles/core/nfs_server/readme.rst, roles/core/nfs_server/vars/main.yml
Previous change added new feature in stable-1.6, but it can break existing systems. This fix is to disable the feature by default, it can be enabled by setting "nfs_server_create_directories_if_not_exist: true".
#895
=> fix: nfs_server - Disable auto directories creation capability by default

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/README.md, collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2, collections/infrastructure/roles/pxe_stack/vars/main.yml
**Update kickstart.cfg.j2 for RedHat to assign  /var/lib/bluebanquise/.ssh to bluebanquise user**
When deploying RedHat based OS on nodes and creating ssh keys from the kickstart.cfg, files in bluebanquise home directory belong to root and not to bluebanquise user. A chown is added.
Added a chown command in the RedHat template file to solve the problem.
=> Update kickstart.cfg.j2 for RedHat to assign  /var/lib/bluebanquise/.ssh to bluebanquise user

collections/infrastructure/roles/pxe_stack/README.md, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless, collections/infrastructure/roles/pxe_stack/vars/main.yml
Fixes  and minor improvements to bluebanquise diskless
- 2.0.2: some refactoring to path handling, this avoids issues with missing "/" in the diskless.yml fole
- 2.0.3: sanitize user input: use strip(), don't accept empty strings, don't allow special characters for image names (POSIX Portable Filename Character Set)
- 2.0.4: Ensure parent of home dir exists, this prevents failure of "useradd" on non-standard home directories
- 2.0.5: Add debug optional parameter (--debug)
- 2.0.6: The tar command to extract bootstrap image may modify uid/gid of files to match the uid/gid of the local node. Adding "--numeric-owner" to keep the original uid/gid. Otherwise, services like sssd / chrony may fail in image.
- 2.0.7: Fix #953 now a new boot.ipxe file is created for clone image
#953 
Note: I have …
=> Fixes to bluebanquise diskless

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/update_reboot/README.md, collections/infrastructure/roles/update_reboot/tasks/main.yml
change the update_reboot role to only reboot the server if something was really updated.
=> Change to only reboot if something was updated

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/clustershell/README.md, collections/infrastructure/roles/clustershell/templates/local.cfg.j2, collections/infrastructure/roles/clustershell/vars/main.yml
- Replaced manual comma placement logic using `loop.first` with the `join(',')` filter to handle node separation.
- This change simplifies the template by removing unnecessary conditional logic for commas and ensures no leading or trailing commas are present in the output.
- The join(',') filter automatically joins the sorted nodes with commas, improving both readability and functionality.
[!983](https://github.com/bluebanquise/bluebanquise/issues/983)
- [ x ] Document introduced changes / variables in role README.md if any
- [ x ] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- [ x ] Update changelog inside role README.md
- [ x ] If not present, please also add your name in the related collection authors list in galaxy.yml
=> fix(clustershell): Unnecessary leading comma in Clustershell template

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/README.md, collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2, collections/infrastructure/roles/pxe_stack/vars/main.yml
The sed command present in the kickstart template has a too inclusive regexp,
resulting in the substitution of a PermitRootLogin parameter description in a documentation block,
which leads to 2 repetitive entries.
So we narrow it down to the line starting with "#PermitRootLogin", which is the actual commented out option.
=> FIX: pxe_stack for RH causing duplicated PermitRootLogin entry in sshd_config

collections/high_availability/galaxy.yml, collections/high_availability/roles/pcs/README.md, collections/high_availability/roles/pcs/tasks/main.yml, collections/high_availability/roles/pcs/vars/main.yml
When the task to load a cib configuration file runs in the secondary mngt node, we get the following error:
`stderr: 'Error: unable to parse new cib: [Errno 2] No such file or directory: ''/root/ha_config.ansible.xml''`
As it happens the task that stores the file previously runs only on mngt1.
This PR changes that in that every node will create the cib file locally.
=> Fix: HA pcs - Task doesn`t find file on running node

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/dns_client/README.md, collections/infrastructure/roles/dns_client/defaults/main.yml
dns_client_domain_name has a default value set, and since it takes precedence over bb_domain_name, which is global,
dns_client always sets resolv.conf to the default value.
The template also has a default value hardcoded directly, so an empty variable will not fail:
`search {{ dns_client_domain_name | default(bb_domain_name, true) | default('cluster.local', true)}}
`
=> Fix: dns_client - DNS client default domain overriding

CHANGELOG, collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/templates/Debian/preseed.cfg.j2, collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2, collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2, collections/infrastructure/roles/pxe_stack/templates/Ubuntu/user-data.j2
Allow to use an hw profile to define partitioning. Precedenced by os if set.
=> Feat: allow to use hw for partitioning along os

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/grafana/README.md, collections/infrastructure/roles/grafana/vars/main.yml
Grafana custom firewall port setting is missing definition of _grafana_default_port_ variable.
=> Fix: grafana - Added missing variable

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/conman/README.md, collections/infrastructure/roles/conman/tasks/main.yml, collections/infrastructure/roles/conman/templates/config.j2, collections/infrastructure/roles/conman/vars/main.yml
When using conman with redfish(ssh) a known_hosts file is create for user conman.
This leads to issues when performing changes in HW, which won't update the file.
=> Feat: comnan - Added ssh settings for conman

collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless
- Recover features of bluebanquise-diskless that were available in SMC 1.x.
- Adapted our patched version of bluebanquise-diskless for BB 3: pxe dir, bluebanquise-bootset, also some improvements were only on BB side and have been integrated here.
- The SELinux feature is present but it has not been properly tested, it was requiring a fix from RedHat (SELinux + boot from live image)
- Tested most features of the tool, and tested boot of reference image. But I have not tested boot of live image yet.
=> bluebanquise-diskless: apply features done for SMC 1.x, update for BB 3

collections/infrastructure/roles/grafana/README.md, collections/infrastructure/roles/grafana/handlers/main.yml, collections/infrastructure/roles/grafana/tasks/install.yml, collections/infrastructure/roles/grafana/vars/main.yml
- Replaced start_services by bb_start_services
- Fixed user creation check error(string to int conversion)
=> Fix: grafana - service start in BB3, user creation error

CHANGELOG, collections/infrastructure/roles/dns_server/README.md, collections/infrastructure/roles/dns_server/templates/forward.j2
The idea is to create aliases that point to the same IP without also being inserted in /etc/hosts.
So this entry:
```
fn_management:
hosts:
mgt1
- interface: eth0
ip4: 10.0.0.10
dns_alias:
- www
mgt2
- interface: eth0
ip4: 10.0.0.20
dns_alias:
- www
```
Will create a foward.zone file with:
```
www IN A 10.0.0.10
www IN A 10.0.0.20
```
A lookup to the webserver should return:
```
www.bluebanquise.example.com has address 10.0.0.10
www.bluebanquise.example.com has address 10.0.0.20
```
Ref:
https://access.redhat.com/solutions/54311
=> Feat: dns_server - round robin load balance

CHANGELOG, collections/infrastructure/roles/dhcp_server/README.md, collections/infrastructure/roles/dhcp_server/defaults/main.yml, collections/infrastructure/roles/dhcp_server/templates/dhcpd.subnet.conf.j2, collections/infrastructure/roles/dhcp_server/vars/main.yml
This PR ports the advanced patterns from the old advanced_dhcp_server, where a complex matching pattern could be written
in external macros.
- Add a parameter _advanced_dhcp_server_enable_patterns_ to enable feature
- Name macro in the option _dhcp_pattern_ of the host network interface
=> Feat: dhcp_server - external patterns

collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless
- Revert change done on images path, now use standard /var/www/html/pxe/diskless  
- Tolerate legacy paths inside tool (diskless/images, diskless/nfs_reference)
=> Revert change diskless path

collections/infrastructure/galaxy.yml
Abusing semantic versioning:
- We want to point out this released is based on 3.2.5
- We should not use "3.2.5" as we have made changes to BB official release
- We don't want to create a non-existent release 3.3.0
- We cannot ask for 3.2.6 with our custom changes
- Idea is to add a "pre-release description" to 3.2.5
- Original idea was "3.2.5-smc", but we may need another release for SMC 2.0.1
- Final solution is "3.2.5-smc2.0.0"
Edit: for release SMC 2.0.1, we will be able to release "3.2.6-smc".
With this possibility, we will release as "3.2.5-smc"
=> Set galaxy version for SMC 2.0.0 release

collections/infrastructure/roles/grafana/tasks/main.yml
- Move wait for db to an earlier point in the role
- Set a timeout of 5 min
=> Wait is now earlier and has a timeout of 5min

CHANGELOG, collections/infrastructure/roles/grafana/README.md, collections/infrastructure/roles/grafana/handlers/main.yml, collections/infrastructure/roles/grafana/tasks/install.yml, collections/infrastructure/roles/grafana/vars/main.yml
A task that manages Grafana service might fail in timeout when using an external database.
This is due to extensive operations performed by Grafana before it returns a positive feedback.
Also fixed restart service handler variables.
=> Fix: grafana - service management timeout

CHANGELOG, collections/infrastructure/plugins/filter/nodeset.py, collections/infrastructure/plugins/filter/nodeset_expand.py, collections/infrastructure/roles/powerman/templates/powerman.conf.j2, collections/infrastructure/roles/powerman/vars/main.yml
ipimipower isn't expanding nodesets with multiple intervals properly, ex:
ipmipower -h head_[0-1]-tail_[0,1]
head_0-tail_[0
head_1-tail_[0
A workaround is to do a prior expansion in powerman config:
ipmipower -h head_0-tail_0,head_0-tail_1,head_1-tail_0,head_1-tail_1
head_0-tail_0
head_0-tail_1
head_1-tail_0
head_1-tail_1
For that purpose a nodeset_expand function was added to nodeset.py.
=> Fix: powerman - Expand powerman nodeset for ipmipower

CHANGELOG, collections/infrastructure/roles/auditd/handlers/main.yml, collections/infrastructure/roles/auditd/tasks/main.yml, collections/infrastructure/roles/auditd/vars/main.yml, collections/infrastructure/roles/conman/handlers/main.yml, collections/infrastructure/roles/conman/tasks/main.yml, collections/infrastructure/roles/conman/vars/main.yml, collections/infrastructure/roles/http_server/handlers/main.yml, collections/infrastructure/roles/http_server/tasks/main.yml, collections/infrastructure/roles/http_server/vars/main.yml, collections/infrastructure/roles/powerman/handlers/main.yml, collections/infrastructure/roles/powerman/tasks/main.yml
Issue detected with some services in High Availability due to a different implementation of the logic to start/enable services.
Seems that `default(true, true)` was causing the task to be executed twice, once with "bb_start_services" false (as intended) and another with "bb_start_services" true (undesired).
The issue has the potential to trigger STONITH if fencing is enabled.
=> Fix services running in both nodes in HA

CHANGELOG, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless, collections/infrastructure/roles/pxe_stack/vars/main.yml
bluebanquise-diskless fails if images path (default /var/www/html/pxe/diskless) contains "lost+found" directory:
```
[INFO] Checking reference images in /var/www/html/pxe/diskless
File /var/www/html/pxe/diskless/lost+found/metadata.yaml does not exist, please re-run pxe_stack role before using the tool.
```
Solution is to add "lost+found" to a list that gets filtered when searching for reference/live images.
=> Fix bluebanquise diskless lost found

CHANGELOG, collections/infrastructure/roles/podman/README.md, collections/infrastructure/roles/podman/templates/registry.service.j2, collections/infrastructure/roles/podman/vars/main.yml
Registry service managed by podman role returns rc=2 when stopped. Update systemd template to show normal deactivation instead of failure when service is stopped.
Tested in RHEL 9.
=> Fix registry failed after stop

CHANGELOG, collections/infrastructure/roles/prometheus/README.md, collections/infrastructure/roles/prometheus/templates/prometheus.yml.j2, collections/infrastructure/roles/prometheus/vars/main.yml
- There was an error in the Prometheus template that considered Alertmanager peers within scrape_configs, which resulted in an attempt by the Prometheus job to access the cluster peers on port 9090 to scrape for metrics. In this case, in an environment with HA, Prometheus is running on only one host through the VIP and it is through it that we must search for metrics.
Wrong:
```yaml
- job_name: 'prometheus_ha'
scrape_interval: 30s
metrics_path: "/prometheus/metrics"
static_configs:
- targets:
- mgt1-ptp:9090
- mgt2-ptp:9090
```
Correct:
```yaml
scrape_configs:
- job_name: 'prometheus_ha'
scrape_interval: 30s
metrics_path: "/prometheus/metrics"
static_configs:
- targets:
- prometheus.example.com:9090
```
- I added HTTPs support in scrape_configs. To access Prometheus through VIP with HTTPS …
=> fix(prometheus): prometheus.yml template

CHANGELOG, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless, collections/infrastructure/roles/pxe_stack/vars/main.yml
- Fix bluebanquise-diskless option 4 link nfs when node runs SELinux ,error were:
```
ERROR: command /usr/bin/grep -q '^smc:' /var/www/html/pxe/diskless/nfs_reference/rhel_9.5_aarch64-ref-standard/etc/passwd || /usr/sbin/useradd  -R /var/www/html/pxe/diskless/nfs_reference/rhel_9.5_aarch64-ref-standard/ -m -c 'SMC user' -d /opt/smc/home -s /bin/bash -p '$6$wDehqATpDnyU8il3$jGFLpIeN4F74xtdFAQfS7n3as9.FkONxpp4wNrNPYrzafdZW0GB3duYXAI95.AhFQEa.lr.3VFwoGL0dj9sDU0' smc failed :(
Report:
Error code: 9
stdout: b'useradd: group smc exists - if you want to add this user to that group, use -g.\n'
```
This error can be fixed by creating "/sys/fs/selinux/enforce" in NFS image with contents "0".
- Second error appeared right after first fix
```
ERROR: command /usr/bin/grep -q '^smc:' …
```
=> Fix bluebanquise-diskless option 4 link nfs when node runs SELinux

CHANGELOG, collections/infrastructure/roles/grafana/handlers/main.yml, collections/infrastructure/roles/grafana/tasks/dashboards.yml, collections/infrastructure/roles/grafana/vars/main.yml
This is complementary to https://github.com/bluebanquise/bluebanquise/pull/1071.
Also remove no_log to show imported dashboards.
=> Fix: grafana - Added retry to service handler

CHANGELOG, collections/infrastructure/roles/conman/templates/conman.conf.j2, collections/infrastructure/roles/conman/vars/main.yml, collections/infrastructure/roles/powerman/templates/powerman.conf.j2, collections/infrastructure/roles/powerman/vars/main.yml
[Fix: powerman - Restore feature to inform credentials via BMC ansible]
[Fix: conman - Restore feature to inform credentials via BMC ansible]
Tested in dev environment by checking the contents of powerman.log and conman.log with different inventories
- IPMI in host inventory
- IPMI in BMC inventory
- REDFISH in host inventory
- REDFISH in BMC inventory
=> Fix conman powerman bmc credentials

CHANGELOG, collections/infrastructure/roles/grafana/tasks/install.yml, collections/infrastructure/roles/grafana/vars/main.yml
There's a remaining ep_firewall variable in grafana role.
=> Fix: grafana: wrong firewall variable name

collections/infrastructure/roles/slurm/tasks/accounting.yml
To create the Slurm database, connection is made with slurm_accounting_mysql_login_user/slurm_accounting_mysql_login_password on a remote database server or via socket access from root on the local node without login/password required (when deploying localy the database) but not with slurm_accounting_storage_user/slurm_accounting_storage_pass
When creating the storage user in the database use first slurm_accounting_storage_user/slurm_accounting_storage_pass if they are set.
Changes in the login/password to use for creating and initializing the database for Slurm.
With a local database no login/password are required as via socket access only root can do this on the management node.
Moreover the database access must be grant to  slurm_accounting_storage_user with …
=> Slurm role fails to deploy and initialize a local mysql database on the management node for accounting.  

CHANGELOG, collections/infrastructure/roles/pxe_stack/tasks/diskless.yml, collections/infrastructure/roles/pxe_stack/vars/main.yml
In pxe_stack theres a task that creates diskless nfs directories structure.
That's ok for when the role runs for the first time, but the task has a "recursive" property that will cause the module
to act on hundreds of thousands of files if a few dozen images are present. This is causing long delays and might even
break the images.
It seems that this task should create the folder and nothing else.
=> Fix: pxe_stack: Dont recursively act on folder

CHANGELOG, collections/infrastructure/roles/podman/README.md, collections/infrastructure/roles/podman/defaults/main.yml, collections/infrastructure/roles/podman/tasks/users.yml, collections/infrastructure/roles/podman/templates/etc/containers/containers.conf.j2, collections/infrastructure/roles/podman/templates/home/containers.conf.j2, collections/infrastructure/roles/podman/vars/main.yml
Fix to podman role:
- File and dir permissions for rootless
- Use default values for network_config_dir and tmp_dir, add comments
- Update containers.conf template for rootless
- Introduce podman_sudo_user to allow bluebanquise user (this is a feature, should be treated separately for BB PR)
- Avoid failure if user in podman_users does not exist
=> Fix podman rootless configuration

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless
Fix: bluebanquise-diskless - allow + character, needed for kernel-64k  in aarch64 images
=> Fix: bluebanquise-diskless - allow + character, needed for kernel-64k  in aarch64 images

collections/infrastructure/galaxy.yml, collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless, collections/infrastructure/roles/pxe_stack/templates/diskless_parameters.yml.j2, collections/infrastructure/roles/pxe_stack/vars/main.yml
Fixes for aarch64 diskless images
- Pass -u <uid> when creating user in diskless reference image so that usermod command does not fail later
- Avoid chroot when configuring SELinux in live image
=> Fix bb diskless aarch64

CHANGELOG, collections/infrastructure/roles/slurm/README.md, collections/infrastructure/roles/slurm/defaults/main.yml, collections/infrastructure/roles/slurm/tasks/accounting_local_mysql.yml, collections/infrastructure/roles/slurm/tasks/main.yml, collections/infrastructure/roles/slurm/tasks/pam_slurm_adopt.yml, collections/infrastructure/roles/slurm/templates/slurm.conf.j2, collections/infrastructure/roles/slurm/vars/RedHat_9.yml
This PR will address 2 sets of commits:
on EL9, the local accounting configuration was using the incorrect unix_socket path, leading to this:
```bash
TASK [bluebanquise.infrastructure.slurm : mysql_db <|> Create slurm_acct_db database] *************************************************************************************************************************************************
Saturday 30 August 2025  01:26:42 +0200 (0:00:00.011)       0:00:23.479 ******* 
fatal: [mngt01]: FAILED! => changed=false 
msg: 'unable to find /root/.my.cnf. Exception message: (2003, "Can''t connect to MySQL server on ''localhost'' ([Errno 2] No such file or directory)")'
```
So, to overcome this, I created a new variable called "slurm_accounting_mysql_unix_socket" on the slurm role so we can keep different …
=> Slurm - Fix local accounting setup + Add slurm_pam_adoption
