roles/core/conman/handlers/main.yml
roles/core/conman/tasks/main.yml

fix missing "}" in conman role
update from with_items to loop
add notify (not fully implemented yet)

bugfix in conman role

---

roles/advanced-core/advanced_dhcp_server/handlers/main.yml
roles/advanced-core/advanced_dhcp_server/tasks/main.yml

Restart the dhcp service when a configuration file change.

Feature: add handler for advanced_dhcp_server

---

roles/addons/prometheus_client/files/nhc_exporter.py
roles/core/repositories_client/tasks/centos_7.yml
roles/core/repositories_client/tasks/centos_8.yml
roles/core/repositories_client/tasks/redhat_7.yml
roles/core/repositories_client/tasks/redhat_8.yml

flake8:
E302 expected 2 blank lines, found 1
E305 expected 2 blank lines after class or function definition, found 1
ansible-lint:
[206] Variables should have spaces before and after: {{ var_name }}

style: make static code analysis happy

---

roles/addons/prometheus_client/files/bb_exporter.py
roles/addons/prometheus_client/files/bb_exporter_plugins/cpu.py
roles/addons/prometheus_client/files/bb_exporter_plugins/mounted.py
roles/addons/prometheus_client/files/bb_exporter_plugins/nhc.py
roles/addons/prometheus_client/files/bb_exporter_plugins/ram.py
roles/addons/prometheus_client/files/bb_exporter_plugins/services.py
roles/addons/prometheus_client/files/bb_exporter_plugins/slurm.py
roles/addons/prometheus_client/templates/bb_exporter.yml.j2
roles/addons/prometheus_server/templates/ipmi_config.yml.j2
roles/addons/prometheus_server/templates/prometheus.yml.j2

Fixing many issues.
Remains time values to correct.

Fix: Fixing prometheus role

---

roles/advanced-core/advanced_dhcp_server/tasks/main.yml

Hello,
We need to add tag in main task.
Regards

Update all roles with tags template,service,package

---

resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/network.yml
roles/macros/network.j2

Major change, will need to play again whole deployment to ensure no issues.

Fix: Allow more main network naming patern

---

roles/core/nic/tasks/main.yml

An wrong ifcfg file is generate even no ip is set in the nic declaration #101

Add test for nic without ip4

---

roles/advanced-core/advanced_dhcp_server/handlers/main.yml
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2

Hi,
I have a new patch with 2 commits to submit.
One to fix a bug. The second to manage services with tags more intelligently.
Regards

[1.1.2]  [advanced_dhcp_server] patch

---

bluebanquise.spec

Install macros and require clustershell (for bluebanquise-playbook).

fix: update specfile to build the RPM

---

roles/core/pxe_stack/files/bootset.py

The output may be too verbose when running the bootset command for
hundreds or thousands of nodes. Let the sysadmin choose to quiet the
output.
Switch from print() to logging and add a new parameter --quiet to set
the logging level to WARNING.

feat: Use Python's logging with bootset

---

resources/documentation/configure_bluebanquise.rst
resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice1-1.yml
resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice2-1.yml
resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice3-1.yml
resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice3-2.yml
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2

(cherry picked from commit 629db3f77f779423bc6a5e93e1aff6c18dbfe696)

[advanced_dhcp_sever] remove references to ntp_ip variable (#153)

---

inventory/group_vars/all/general_settings/external.yml
roles/core/repositories_client/tasks/centos_7.yml
roles/core/repositories_client/tasks/centos_8.yml
roles/core/repositories_client/tasks/redhat_7.yml
roles/core/repositories_client/tasks/redhat_8.yml

(cherry picked from commit ec9e900ce740390054df49636262183a6a8ab68f)

Backport repositories configuration

---

.github/workflows/molecule-actions.yml

- distro:
- centos7
- centos8
- role:
- core/display_tuning
- core/dns_client
- core/dns_server
- core/time
- addons/clustershell
- addons/users_basic

ci: run Molecule test with GitHub actions

---

.github/workflows/molecule-actions.yml
roles/core/log_client/.yamllint
roles/core/log_client/molecule/default/INSTALL.rst
roles/core/log_client/molecule/default/converge.yml
roles/core/log_client/molecule/default/files/expected_rsyslog.conf
roles/core/log_client/molecule/default/molecule.yml
roles/core/log_client/molecule/default/prepare.yml
roles/core/log_client/molecule/default/verify.yml
roles/core/log_server/.yamllint
roles/core/log_server/molecule/default/INSTALL.rst
roles/core/log_server/molecule/default/converge.yml
roles/core/log_server/molecule/default/files/expected_rsyslog.conf
roles/core/log_server/molecule/default/molecule.yml
roles/core/log_server/molecule/default/prepare.yml
roles/core/log_server/molecule/default/verify.yml

Molecule tests for:
- log_client
- log_server

Adding molecule tests for log_client and log_server

---

resources/documentation/learn_ansible.rst

Ansible part improvement of the documentation.

Fix: improve Ansible documentation

---

roles/core/conman/templates/conman.conf.j2

Related to https://github.com/bluebanquise/bluebanquise/issues/169

Fix: conman template issue

---

roles/core/time/vars/main.yml

fix: role time need tzdata for Ubuntu

---

resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
roles/core/pxe_stack/templates/kickstart.cfg.j2

Add post and pre script ability.
Missing preseed and autoyast, should be added later when adding these distributions (soon).

Feat: Add post and pre script ability to autoinstall

---

resources/documentation/configure_bluebanquise.rst
resources/documentation/deploy_bluebanquise.rst
resources/documentation/install_first_management.rst
resources/documentation/learn_ansible.rst
resources/documentation/vocabulary.rst
roles/core/pxe_stack/readme.rst

Small multiple fix in the documentation.

Fix: fix small issues in documentation

---

roles/core/dns_server/molecule/default/converge.yml
roles/core/dns_server/tasks/main.yml

fix: use management_networks_naming in dns_server

---

.github/workflows/molecule-actions-core-time.yml
.github/workflows/molecule-actions.yml
resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml
resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
roles/core/time/molecule/default/converge.yml
roles/core/time/molecule/default/molecule.yml
roles/core/time/molecule/default/verify.yml
roles/core/time/readme.rst
roles/core/time/templates/chrony.conf.j2

- fix: make time pool and server mutually exclusive
- fix: limit chrony local stratum to max value 15
- fix: define external xor internal ntp sources
- ci: enhance time unit tests with molecule
See #166 for details.

fix: multiple issues with time role (#166)

---

roles/core/conman/molecule/default/molecule.yml
roles/core/conman/templates/conman.conf.j2

fix: use equipment_authentication in conman

---

resources/examples/multi_icebergs_cluster/inventory/cluster/nodes/iceberg1/managements.yml
roles/core/nic/readme.rst
roles/core/nic/tasks/main.yml
roles/core/nic/templates/ifcfg.j2

missing good TYPE, missing VLAN_ID, missing PHYSDEV

Fix: solve VLAN issues

---

resources/documentation/conf.py

https://github.com/bluebanquise/bluebanquise/issues/195

Fix molecule auto inclusion in documentation

---

ansible.cfg

https://github.com/bluebanquise/bluebanquise/issues/239

Fix: ansible_managed

---

.github/workflows/molecule-actions-core-ssh_master.yml
roles/core/ssh_master/.yamllint
roles/core/ssh_master/molecule/default/INSTALL.rst
roles/core/ssh_master/molecule/default/converge.yml
roles/core/ssh_master/molecule/default/molecule.yml
roles/core/ssh_master/molecule/default/prepare.yml
roles/core/ssh_master/molecule/default/verify.yml

Create 3 platforms:
- icebergs-off: icebergs_system = false
- icebergs-on: icebergs_system = true
- hostkey_checking: do not disable StrictHostKeyChecking
Add 5 extra hosts to generate the configuration file:
- 1 fake-mgmt2, mainly for icebergs_system = true tests
- 4 fake-hostX

ci: setup molecule unit test for ssh_master role

---

.github/workflows/molecule-actions-addons-clustershell.yml
.github/workflows/molecule-actions-addons-users_basic.yml
.github/workflows/molecule-actions-core-bluebanquise.yml
.github/workflows/molecule-actions-core-conman.yml
.github/workflows/molecule-actions-core-display_tuning.yml
.github/workflows/molecule-actions-core-dns_client.yml
.github/workflows/molecule-actions-core-dns_server.yml
.github/workflows/molecule-actions-core-log_client.yml
.github/workflows/molecule-actions-core-log_server.yml
.github/workflows/molecule-actions-core-repositories_client.yml
.github/workflows/molecule-actions-core-ssh_master.yml
.github/workflows/molecule-actions-core-time.yml

@strus38 sent me a note with a tip to colorize the output of molecule tests. It should definitely help to read the output of the ci tests.

ci: make output pretty and colorful

---

.github/TEST_MATRIX.md
.github/workflows/molecule-actions-core-time.yml

ci: remove Ubuntu 18.04 from molecule core/time

---

bluebanquise.spec
roles/addons/powerman/handlers/main.yml
roles/addons/powerman/readme.rst
roles/addons/powerman/tasks/main.yml
roles/addons/powerman/templates/powerman.conf.j2
roles/addons/powerman/vars/main.yml

Add task, handler and template.
Missing readme.

Feat: Add powerman role

---

.github/TEST_MATRIX.md
.github/workflows/molecule-actions-core-firewall.yml
roles/core/firewall/.yamllint
roles/core/firewall/molecule/default/INSTALL.rst
roles/core/firewall/molecule/default/converge.yml
roles/core/firewall/molecule/default/molecule.yml
roles/core/firewall/molecule/default/verify.yml
roles/core/firewall/readme.rst
roles/core/firewall/tasks/RedHat.yml
roles/core/firewall/tasks/main.yml
roles/core/firewall/vars/RedHat.yml
roles/core/firewall/vars/main.yml

Read the readme first. :-)
Add new role core/firewall. Only support RHEL/CentOS.
This role should integrate seamlessly with the firewalld tasks in the core roles.

feat: add role core/firewall

---

resources/examples/simple_cluster/group_vars/all/general_settings/network.yml
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.conf.j2

Backport of https://github.com/bluebanquise/bluebanquise/pull/265
Regards

[stable-1.1] Add ignore-client-uids parameter in dhcpd.conf

---

roles/core/hosts_file/templates/hosts.j2

hello,
the generation of bmc alias was bad in hosts file
Please accept this change.
thank you

[Stable-1.1] update hosts.j2 after a little problem

---

inventory/group_vars/all/general_settings/network.yml

Backport to https://github.com/bluebanquise/bluebanquise/pull/265

[Stable-1.1] Add ignore-client-uids parameter in network.yml

---

roles/addons/diskless/readme.rst

Started a new documentation for the diskless role, including usage examples for disklessset and bootset.

New diskless documentation

---

roles/advanced-core/advanced_dhcp_server/readme.rst
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.conf.j2
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2
roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
roles/advanced-core/advanced_dhcp_server/vars/main.yml

Update advanced dhcp server to use new NIC syntax in inventory.

Fix: Update advanced dhcp server to new nic syntax

---

roles/core/hosts_file/templates/hosts.j2

A nasty bug, found yesterday evening while working on diskless

Fix: bug in hosts_file template

---

roles/core/nic/readme.rst

[nic] renaming key 'name' in 'interface' in readme file

---

.github/TEST_MATRIX.md
.github/workflows/molecule-actions-addons-clustershell.yml
.github/workflows/molecule-actions-addons-root_password.yml
.github/workflows/molecule-actions-addons-users_basic.yml
.github/workflows/molecule-actions-core-conman.yml
.github/workflows/molecule-actions-core-display_tuning.yml
.github/workflows/molecule-actions-core-dns_client.yml
.github/workflows/molecule-actions-core-dns_server.yml
.github/workflows/molecule-actions-core-log_client.yml
.github/workflows/molecule-actions-core-ssh_master.yml
.github/workflows/molecule-actions-core-time.yml

ci: remove ubuntu tests

---

roles/addons/diskless/files/disklessset.py

Hello,
In this PR, there are several things to know :
- https://github.com/bluebanquise/bluebanquise/pull/299 fixing
- adding a SELinux feature in livenet
- adding an error handling with dnf
- fixing dracut InitRD generation with specifical kernel version (--kver)
Regards,
@hmeAtos

[Diskless] bugs fixing and SELinux feature

---

roles/core/pxe_stack/files/bootset.py

Group output of bootset status.
Before:
```
- c001 : diskless
- c002 : diskless
- c003 : diskless
- c004 : diskless
- c005 : diskless
- c006 : diskless
- c007 : diskless
- c008 : diskless
- c009 : diskless
- c010 : diskless
- login1 : diskless
- login2 : diskless
- login3 : diskless
- login4 : diskless
- login5 : diskless
- management2 : osdeploy
- management3 : disk
- management4 : disk
```
After:
```
Diskfull: management[3-4]
Next boot deployment: management2
Diskless image(s):
- selinux4: c[001-010]
- selinux1: login[1-5]
```

fix: group bootset status per boot type and image

---

.github/workflows/molecule-actions-addons-clustershell.yml
.github/workflows/molecule-actions-addons-root_password.yml
.github/workflows/molecule-actions-addons-users_basic.yml
.github/workflows/molecule-actions-core-bluebanquise.yml
.github/workflows/molecule-actions-core-conman.yml
.github/workflows/molecule-actions-core-display_tuning.yml
.github/workflows/molecule-actions-core-dns_client.yml
.github/workflows/molecule-actions-core-dns_server.yml
.github/workflows/molecule-actions-core-firewall.yml
.github/workflows/molecule-actions-core-log_client.yml
.github/workflows/molecule-actions-core-log_server.yml
.github/workflows/molecule-actions-core-repositories_client.yml
.github/workflows/molecule-actions-core-ssh_master.yml
.github/workflows/molecule-actions-core-time.yml
.github/workflows/static_analysis.yml

ci: do not install ansible 2.9.12

---

roles/addons/diskless/files/disklessset.py
roles/addons/diskless/readme.rst
roles/addons/diskless/tasks/main.yml
roles/addons/diskless/vars/RedHat.yml
roles/addons/diskless/vars/RedHat_7.yml
roles/addons/diskless/vars/RedHat_8.yml
roles/core/nic/tasks/main.yml
roles/core/set_hostname/tasks/main.yml

Adding missing diskless images customizing / playbook running capabilty.
Still a draft
Missing documentation in the readme for now. In next commit.

Fix: Add missing playbook run capability in livenet images

---

roles/core/nfs_client/vars/RedHat.yml
roles/core/nfs_client/vars/Ubuntu.yml

Should be a list. If not:
TASK [nfs_client : package █ Install n f s - u t i l s packages] ***********************************************************************************************************************
Tuesday 18 August 2020  22:09:37 +0200 (0:00:00.042)       0:00:15.273 ********
changed: [c001]

Fix: small issue in nfs_client role packages list

---

CONTRIBUTING.md
roles/core/ssh_slave/readme.rst

doc: replace all_equipment with equipment_all

---

roles/core/repositories_client/readme.rst

Fix: Missing code blocks in repositories_client role

---

roles/addons/prometheus_server/defaults/main.yml
roles/addons/prometheus_server/tasks/main.yml
roles/addons/prometheus_server/templates/karma.yml.j2

Karma was partially missing from the prometheus_server role.
karma.yml file is from @sobrase

Fix: Add missing karma service and configuration

---

CHANGELOG.md
resources/packaging/bluebanquise.spec

Based on #321, but for RC2 release. To merge at time of release.

Release 1.3rc2

---

roles/advanced-core/advanced_dns_server/handlers/main.yml
roles/advanced-core/advanced_dns_server/tasks/main.yml

fix: typo in role advanced_dns_server

---

resources/documentation/monitoring/grafana.rst

changed grafana.rst, because prometheus_server role doesn't install grafana anymore, so only manual install of grafana available.

Update of grafana.rst

---

resources/documentation/monitoring/grafana.rst

changed info to information in grafana.rst in order to update documentation

changed info to information in grafana.rst

---

README.md

I changed my GitHub account @actatux -> @btravouillon

Add GitHub account @btravouillon to README

---

resources/packaging/bluebanquise.spec

Install new internal inventory.
Add python requirements for Ansible filters.
Add CHANGLOG.md to documentation in RPM spec file.

fix: update bluebanquise.spec for 1.3

---

resources/documentation/monitoring/node_exporter.rst

Made the phrase look more like a suggestion rather than an obligation

Rephrasing of node_exporter not running on nodes

---

roles/core/repositories_client/molecule/default/molecule.yml
roles/core/repositories_client/molecule/default/prepare.yml
roles/core/repositories_client/molecule/default/verify.yml
roles/core/repositories_client/readme.rst
roles/core/repositories_client/tasks/centos_7.yml
roles/core/repositories_client/tasks/centos_8.yml

See #288 
Also add new molecule tests for the role repositories_client with several configuration combination.

fix: disable distro repos even when 'os' is a dict

---

roles/addons/diskless/files/disklessset.py
roles/addons/diskless/readme.rst

Hello BB'Team,
I add example and clarification which are reported by less experienced users.
Regards,
@hmeAtos

[diskless] adding example and clarification

---

roles/addons/diskless/readme.rst

Restore deleted line with latest PR.
See
https://github.com/bluebanquise/bluebanquise/commit/14c445719e871b5fbb8d7908fdad742e47063a18

Fix: diskless - readme

---

resources/documentation/monitoring/prometheus.rst

Small typo issue in YAML example.

Fix: documentation - prometheus

---

roles/addons/diskless/files/disklessset.py

select_from_list() must return an integer from the user selection, in
the range 1..len(list_from). Any other value is not valid. The function
will loop recursively until the user enter a valid value or exit the
programm.
Parameter index_modifier defaults to -1 since every call to the function
is using this value.
Avoid useless type casting int(str(int(x))).
See: #296

fix: force to enter integer in select_from_list()

---

roles/addons/diskless/files/disklessset.py

fix: umount diskless image when workdir exists

---

roles/addons/diskless/files/disklessset.py

Backport of several bugfixes for disklessset.

fix: backports for disklessset (#379 #380 #381)

---

CHANGELOG.md
resources/documentation/deploy_bluebanquise.rst

Based on user feedback in the field, some instruction were not clear or
even wrong.

doc: rephrase and fix the CHANGELOG

---

CHANGELOG.md
resources/packaging/bluebanquise.spec
roles/addons/Lmod/readme.rst
roles/addons/Lmod/tasks/main.yml
roles/addons/Lmod/templates/modules_extra_path.sh.j2
roles/addons/Lmod/vars/RedHat.yml

Add Lmod and configure custom path if needed.

Feat: Add Lmod role

---

roles/addons/openldap_server/tasks/main.yml
roles/addons/openldap_server/vars/RedHat_7.yml
roles/addons/openldap_server/vars/RedHat_8.yml
roles/addons/openldap_server/vars/main.yml
roles/core/conman/molecule/default/prepare.yml
roles/core/conman/tasks/main.yml
roles/core/conman/vars/RedHat_7.yml
roles/core/conman/vars/RedHat_8.yml
roles/core/conman/vars/main.yml
roles/core/nfs_client/vars/RedHat.yml
roles/core/nfs_client/vars/RedHat_7.yml
roles/core/nfs_client/vars/RedHat_8.yml

seboolean module requires python selinux libs

fix: missing packages in conman role

---

resources/documentation/install_first_management.rst

Remove disabling firewall since stack now handles it.
Increase minimum hdd requirement.
Too much people fall in this firewall issue.

Fix: documentation - corrections based on feedback

---

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2

Hi,
Backport to https://github.com/bluebanquise/bluebanquise/pull/408
Regards

[stable-1.3] [advanced_dhcp_server] whitespace too long, buffer overflow.

---

roles/addons/diskless/files/disklessset.py

Hi,
backport to https://github.com/bluebanquise/bluebanquise/pull/410 please
Regards

[stable-1.3][diskless] customized image boots with incorrect interfaces names

---

roles/addons/diskless/readme.rst

Hello,
Backport to https://github.com/bluebanquise/bluebanquise/pull/411
regards

[diskless] The time role isn't functional for a custom diskless image

---

roles/addons/diskless/files/disklessset.py

fix: use regex to replace kernel in boot.ipxe

---

CHANGELOG.md

Add missing entries, we need to keep this file up to date and require a change when PR.

Fix: CHANGELOG.md - Add missing entries

---

roles/addons/diskless/readme.rst

Refer to #420 
This tags allows the pre_task to always run, whatever the tags used, since it is only internal mechanism and mandatory for other roles to run properly in the diskless chroot.

Doc: Diskless - Improve the readme

---

resources/documentation/monitoring/ha_cluster_exporter.rst
resources/documentation/monitoring/slurm_exporter.rst
roles/addons/prometheus_client/readme.rst

See https://github.com/bluebanquise/bluebanquise/issues/429

Doc: Inform that some exporter are not provided as packages

---

roles/addons/diskless/readme.rst

Some output were outdated and inaccurate. (Fixes #374)
Improve the 'Customizing Livenet image' section (Fixes #420):
- add special tag 'always' to readme
- use variable 'image_name' in example playbook
(cherry picked from commit 6919146747c6436108082ebfee1aced39807cf3d)

doc: improve diskless readme

---

roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/tasks/main.yml
roles/core/pxe_stack/vars/RedHat_7.yml
roles/core/pxe_stack/vars/RedHat_8.yml
roles/core/pxe_stack/vars/Ubuntu.yml

For 8 major only.
Also still possible to force atftp installation using precedence.

Feat: pxe_stack - Add fbtftp for RHEL/CentOS 8

---

roles/addons/clone/readme.rst
roles/core/pxe_stack/defaults/main.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/templates/menu.ipxe.j2

Fix: core/pxe_stack - Allow to disable clone entries in menu

---

roles/advanced-core/advanced_dhcp_server/readme.rst
roles/core/dhcp_server/readme.rst

Fix: core/dhcp_server|adv_core/adv_dhcp_server up readme

---

roles/core/nic/readme.rst

Hi guys,
I added some explanations on the VLAN which were not clear to some users.
Regards,
Hamid

[nic] README VLAN add an additional explanation

---

roles/core/nic/readme.rst

Hi guys,
I added some explanations on the VLAN which were not clear to some users.
Regards,
Hamid

[nic] add an additional explanation (Backport To Stable-1.3)

---

CHANGELOG.md
resources/documentation/roles.rst
resources/packaging/bluebanquise.spec
roles/addons/nhc/defaults/main.yml
roles/addons/nhc/readme.rst
roles/addons/nhc/tasks/main.yml
roles/addons/nhc/templates/nhc.conf.j2
roles/addons/nhc/vars/RedHat.yml
roles/addons/nhc/vars/main.yml

Feat: addons/nhc

---

roles/advanced-core/advanced_dns_server/templates/forward.j2

(cherry picked from commit 704d2eeb1cec77f667bf727bd69cf9f143b413ff)

Fix: adv_core/adv_dns_server

---

CHANGELOG.md
roles/core/log_client/defaults/main.yml
roles/core/log_client/readme.rst
roles/core/log_client/templates/rsyslog.conf.j2
roles/core/log_client/vars/main.yml

Pull request following issue #466 , about rsyslog verbosity configuration

Add verbosity variable in log_client (#466)

---

roles/core/nfs_client/tasks/main.yml

Fix: core/nfs_client - Bad condition

---

roles/core/nfs_client/tasks/main.yml

* Fix: core/nfs_client - Bad condition
Fix bad conditional
* Fix: core/nfs_client - Add bool filter to conditional
(cherry picked from commit 92d937d5e7e3a840e4452eff65c9905ae8adb82c)

Fix: core/nfs_client - Bad condition (#483)

---

CHANGELOG.md
resources/packaging/bluebanquise.spec
roles/addons/kernel_config/defaults/main.yml
roles/addons/kernel_config/readme.rst
roles/addons/kernel_config/tasks/main.yml
roles/addons/kernel_config/vars/main.yml

Add kernel parameters and sysctl support.
See readme.

Feat: addons/kernel_config - role creation

---

resources/podman/Dockerfile
resources/podman/README.md

Not for production for the time being.
I am using this Dockerfile a lot, and thought it would be cool to share it with all.
It allows to deploy the whole stack into a single container. Very useful for destructive tests or to test a new release on a cluster in production.

Feat: podman - Create Dockerfile

---

README.md

Prepare next steps.
@johnnykeats have a look 😉

Fix: README - Update main readme

---

roles/core/firewall/handlers/main.yml
roles/core/firewall/readme.rst
roles/core/firewall/tasks/RedHat.yml
roles/core/firewall/vars/main.yml

Allow to create a new zone to use with FirewallD.

feat: ensure firewalld zones exist

---

roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2

Fix a missing setting of current_hostvars variable.

bug fix: missing setting of current_hostvars

---

roles/core/nfs_server/readme.rst

Add a note in nfs-server readme about exported directories that must be created before applying the role

feat: minor disclaimer on nfs server role readme

---

CHANGELOG.md
resources/documentation/deploy_bluebanquise.rst
roles/core/pxe_stack/files/bootset.py
roles/core/pxe_stack/molecule/default/verify.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/tasks/main.yml

Fix issue described here: https://github.com/bluebanquise/bluebanquise/issues/482

Fix: core/pxe_stack - Update bootset configuration path

---

roles/core/pxe_stack/templates/kickstart.cfg.j2

RHEL 8.3 introduces change 
See https://bugzilla.redhat.com/show_bug.cgi?id=1881974

Fix: core/pxe_stack - Fix bad hostname issue

---

roles/core/log_client/handlers/main.yml
roles/core/log_client/tasks/main.yml
roles/core/log_server/handlers/main.yml
roles/core/log_server/readme.rst
roles/core/log_server/tasks/main.yml

Fix: log_server and client names

---

resources/data_model.md

Data model, to be a reference.

Feat: data_model - creation

---

CHANGELOG.md
roles/core/set_hostname/defaults/main.yml
roles/core/set_hostname/molecule/default/converge.yml
roles/core/set_hostname/readme.rst
roles/core/set_hostname/tasks/main.yml
roles/core/set_hostname/vars/main.yml

Add FQDN capability for set_hostname.
Request made for an HPC cluster. Seems reasonable.

Feat: set_hostname - Add fqdn capability

---

README.md

Update main README to better explain what the stack is made for, and what is supported.

Fix: README - Update

---

CHANGELOG.md

I forgot to add the CHANGELOG entry for PR #559

Fix: CHANGELOG - Add missing entry for 559

---

CHANGELOG.md
roles/addons/diskless/readme.rst

Backport doc change from master to stable-1.4.1

Docs: diskless - firewall doesn't work in chroot (#569)

---

CHANGELOG.md
roles/core/filesystem/readme.rst
roles/core/filesystem/tasks/main.yml
roles/core/modprobe/readme.rst
roles/core/modprobe/tasks/main.yml
roles/core/mount/readme.rst
roles/core/mount/tasks/main.yml
roles/core/parted/readme.rst
roles/core/parted/tasks/main.yml
roles/core/sudoers/readme.rst
roles/core/sudoers/tasks/main.yml

Few basic roles to automate basic tasks.

Basic roles

---

CHANGELOG.md
roles/core/ssh_master/readme.rst
roles/core/ssh_master/templates/config.j2
roles/core/ssh_master/vars/main.yml

Add way to inject custom config in ssh config file.

Feat: ssh_master - Add custom config variable

---

CHANGELOG.md
roles/core/log_client/readme.rst
roles/core/log_client/tasks/main.yml
roles/core/log_client/vars/main.yml
roles/core/log_server/readme.rst
roles/core/log_server/tasks/main.yml
roles/core/log_server/vars/main.yml
roles/core/time/readme.rst
roles/core/time/tasks/main.yml
roles/core/time/vars/main.yml

Add custom conf path ability using defaults mechanism.

Feat: time, rsyslog - Add custom conf path

---

roles/core/powerman/tasks/main.yml
roles/core/powerman/templates/powerman.conf.j2

Credits goes to @btravouillon
From https://github.com/bluebanquise/bluebanquise/pull/549

Fix: powerman - Allow bigger configurations

---

CHANGELOG.md
roles/core/dns_server/molecule/default/molecule.yml
roles/core/dns_server/readme.rst
roles/core/dns_server/templates/forward.j2
roles/core/dns_server/templates/reverse.j2
roles/core/dns_server/vars/main.yml

Improve dns_server role performances, as it is way to slow in the current state.

Fix: dns_server - improve role performances

---

CHANGELOG.md
roles/advanced_core/advanced_dhcp_server/readme.rst
roles/advanced_core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
roles/advanced_core/advanced_dhcp_server/vars/main.yml
roles/core/conman/readme.rst
roles/core/conman/templates/conman.conf.j2
roles/core/conman/vars/main.yml
roles/core/dhcp_server/readme.rst
roles/core/dhcp_server/templates/dhcpd.subnet.conf.j2
roles/core/dhcp_server/vars/main.yml
roles/core/hosts_file/readme.rst
roles/core/hosts_file/templates/hosts.j2
roles/core/hosts_file/vars/main.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/templates/nodes_parameters.yml.j2
roles/core/pxe_stack/vars/main.yml
roles/core/ssh_master/readme.rst
roles/core/ssh_master/templates/config.j2
roles/core/ssh_master/vars/main.yml

Random changed tasks status caused by unsorted ranges.
Solves issue https://github.com/bluebanquise/bluebanquise/issues/610

Fix: all - Prevent random changed tasks status

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature_request.md

BlueBanquise project is growing, need more under the hood things.

Feat: github - Issues templates

---

resources/equipment_profiles/generic/nvidia_gpu.yml
resources/equipment_profiles/generic/opensuse_leap_15.yml
resources/equipment_profiles/generic/redhat_raid_by-path.yml
resources/equipment_profiles/generic/ubuntu_18.yml
resources/equipment_profiles/models/asus/Z10PA-U8.yml
resources/equipment_profiles/models/dell/R610.yml
resources/equipment_profiles/models/dell/R730.yml
resources/equipment_profiles/models/fujistu/RX200_S8.yml
resources/equipment_profiles/models/intel/HNS2600BPB.yml
resources/equipment_profiles/models/supermicro/2028R-DE2CR24L.yml
resources/equipment_profiles/models/supermicro/X9SRi-F.yml

Attempt to gather as much as possible known equipment profiles to create a data base for users.
Do not hesitate to add more.

Doc: Add more equipment_profiles

---

CHANGELOG.md
roles/core/nfs_client/defaults/main.yml
roles/core/nfs_client/readme.rst
roles/core/nfs_client/tasks/main.yml
roles/core/nfs_client/vars/main.yml

Fix issue https://github.com/bluebanquise/bluebanquise/issues/567 by adding a new variable able to handle multiple sebooleans.

Feat: nfs_client - Change sebooleans input variables

---

.github/TEST_MATRIX.md
.github/workflows/molecule-actions-core-pam_limits.yml
CHANGELOG.md
roles/core/pam_limits/.yamllint
roles/core/pam_limits/molecule/default/converge.yml
roles/core/pam_limits/molecule/default/molecule.yml
roles/core/pam_limits/molecule/default/prepare.yml
roles/core/pam_limits/molecule/default/verify.yml
roles/core/pam_limits/readme.rst
roles/core/pam_limits/tasks/main.yml
roles/core/pam_limits/vars/main.yml

Need ulimits to restrict nasty users on login nodes.
(mpirun -n 1024 .....)

Feat: pam_limits role creation

---

roles/core/diskless/readme.rst

Fix: diskless - Update readme.rst regarding GPG keys

---

CHANGELOG.md
roles/core/bluebanquise/readme.rst
roles/core/bluebanquise/vars/RedHat.yml
roles/core/bluebanquise/vars/RedHat_7.yml
roles/core/bluebanquise/vars/Ubuntu.yml
roles/core/bluebanquise/vars/Ubuntu_20.yml
roles/core/bluebanquise/vars/main.yml

Fix: bluebanquise - Add missing bluebanquise_filter package

---

CHANGELOG.md
roles/core/pxe_stack/molecule/default/prepare.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/templates/Ubuntu/preseed.cfg.j2
roles/core/pxe_stack/templates/Ubuntu/user-data.j2
roles/core/pxe_stack/vars/main.yml

Fix: pxe_stack - Missing efi bootorder for ubuntu

---

CHANGELOG.md
roles/core/ssh_client/readme.rst
roles/core/ssh_client/templates/config.j2
roles/core/ssh_client/vars/main.yml

Fix: ssh_client - Issue with empty network interfaces

---

CHANGELOG.md
resources/data_model.md
roles/core/conman/readme.rst
roles/core/conman/templates/conman.conf.j2
roles/core/conman/vars/main.yml
roles/core/powerman/readme.rst
roles/core/powerman/templates/powerman.conf.j2
roles/core/powerman/vars/main.yml

Add support for external BMC
Add support for advanced credentials

Feat: conman - Add #639 related feature

---

roles/core/clustershell/templates/local.cfg.j2

Hi!
As requested, proposing a PR to fix an idempotency problem in role 'clustershell'.  Issue 673.
Thanks for the great job!

fix an idempotency problem of role clustershell - issue 673

---

CHANGELOG.md
resources/examples/automatic_tests_cluster/inventory/cluster/nodes/computes.yml
resources/examples/automatic_tests_cluster/inventory/group_vars/equipment_typeC_Opensuse_153/equipment_profile.yml
resources/examples/automatic_tests_cluster/inventory/group_vars/equipment_typeC_Redhat_7/equipment_profile.yml
resources/examples/automatic_tests_cluster/inventory/group_vars/equipment_typeC_Redhat_8/equipment_profile.yml
resources/examples/automatic_tests_cluster/inventory/group_vars/equipment_typeC_Ubuntu_2004/equipment_profile.yml
roles/core/pxe_stack/defaults/main.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/tasks/client_os/Suse.yml
roles/core/pxe_stack/templates/RedHat/kickstart.cfg.j2
roles/core/pxe_stack/templates/Suse/autoyast.xml.j2
roles/core/pxe_stack/templates/Ubuntu/preseed.cfg.j2
roles/core/pxe_stack/templates/Ubuntu/user-data.j2
roles/core/pxe_stack/vars/main.yml

Allow to choose between root or sudo user when deploying OS.
Default now goes to sudo user.

Feat: pxe_stack - Allow root or sudouser

---

roles/core/pxe_stack/templates/Suse/autoyast.xml.j2
roles/core/pxe_stack/vars/Suse.yml

- Corrected sudo package install logic in autoyast template
- Added tftp service for SLES 15/OpenSUSE 15

Corrected pxe_stack for SUSE based OSes

---

roles/core/pxe_stack/defaults/main.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/templates/Suse/autoyast.xml.j2
roles/core/pxe_stack/templates/Suse/autoyast_sles12.xml.j2
roles/core/pxe_stack/vars/main.yml

Updated SUSE/OpenSUSE autoyast templates to handle repos better and to allow the OpenSUSE online repos to be disabled during installation for offline installs.

Added pxe_stack_opensuse_preserve_sources_list to pxe_stack role

---

CHANGELOG.md
resources/examples/automatic_tests_cluster/inventory/cluster/groups/equipment_groups
resources/examples/automatic_tests_cluster/inventory/cluster/groups/master_groups
resources/examples/automatic_tests_cluster/inventory/cluster/nodes/computes.yml
resources/examples/automatic_tests_cluster/inventory/cluster/nodes/logins.yml
resources/examples/automatic_tests_cluster/inventory/cluster/nodes/managements.yml
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/tasks/client_os/DGX.yml
roles/core/pxe_stack/tasks/client_os/RedHat.yml
roles/core/pxe_stack/tasks/client_os/Suse.yml
roles/core/pxe_stack/tasks/client_os/Ubuntu.yml
roles/core/pxe_stack/vars/main.yml

Fix: pxe_stack - Prevent crash when empty ep group

---

CHANGELOG.md
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/vars/main.yml
roles/core/repositories_client/readme.rst
roles/core/repositories_client/vars/main.yml
roles/core/ssh_remote_keys/readme.rst
roles/core/ssh_remote_keys/tasks/main.yml
roles/core/ssh_remote_keys/vars/main.yml

Fix #715 issue
@wlln please check if it is ok for you 😊 
Once merged, 1.6 release.

Fix: ssh - Allow keys to sudo user folder

---

CHANGELOG.md
roles/core/pxe_stack/readme.rst
roles/core/pxe_stack/templates/nodes_parameters.yml.j2
roles/core/pxe_stack/vars/main.yml

Solves:
* https://github.com/bluebanquise/bluebanquise/issues/721
* https://github.com/bluebanquise/bluebanquise/issues/720

Fix: pxe_stack - Allow better static network

---

roles/core/diskless/readme.rst

Just fixing 2 typos, "unount" to "unmount"

Just fixing typos on readme.rst

---

roles/core/nfs_server/vars/RedHat.yml

Fix: solves #740

---

collections/infrastructure/galaxy.yml
collections/infrastructure/plugins/modules/networkd.py

Feat nic check mode

---

collections/infrastructure/roles/dns_server/README.md
collections/infrastructure/roles/dns_server/templates/forward.j2
collections/infrastructure/roles/dns_server/vars/main.yml
collections/infrastructure/roles/hosts_file/README.md
collections/infrastructure/roles/hosts_file/templates/hosts.j2
collections/infrastructure/roles/hosts_file/vars/main.yml

Add optional alias for every network interface.
Impacts: dns_server and hosts_file roles.

Add optional alias to every interface. #756.

---

collections/security/galaxy.yml
collections/security/roles/google_authenticator/README.md
collections/security/roles/google_authenticator/tasks/main.yml
collections/security/roles/google_authenticator/vars/RedHat.yml
collections/security/roles/google_authenticator/vars/Ubuntu.yml
collections/security/roles/google_authenticator/vars/main.yml

Just adding First version of google_authenticator role.

added google_authentication role

---

collections/hpc/roles/slurm/README.md
collections/hpc/roles/slurm/templates/slurm.conf.j2
collections/hpc/roles/slurm/vars/main.yml

hpc/slurm: use nodeset filter to improve partition definition readability in slurm.conf

---

CHANGELOG.md
roles/core/log_server/readme.rst
roles/core/log_server/templates/rsyslog.conf.j2
roles/core/log_server/templates/rsyslog_logrotate.j2

Backport for PR #771  into stable-1.6
(cherry picked from commit ec779efdd7481135205424569c5890a86db9ee70)

(backport for BB 1.6) fix: rsyslog - 768 bug rsyslog server not writing locally apps logs not being forwarded

---

collections/hpc/roles/slurm/README.md
collections/hpc/roles/slurm/defaults/main.yml
collections/hpc/roles/slurm/tasks/accounting.yml
collections/hpc/roles/slurm/tasks/compute_configfull.yml
collections/hpc/roles/slurm/tasks/controller.yml
collections/hpc/roles/slurm/tasks/main.yml
collections/hpc/roles/slurm/tasks/submitter.yml
collections/hpc/roles/slurm/templates/cgroup.conf.j2
collections/hpc/roles/slurm/templates/slurmdbd.conf.j2
collections/hpc/roles/slurm/vars/main.yml

Apply consistent naming with new lowercase convention in defaults/main.yml.

hpc/slurm: fix variables naming CamelCase -> lowercase

---

.github/workflows/el9.yml
.github/workflows/static_analysis.yml
.github/workflows/u20.yml
.github/workflows/u22.yml

Fix: enable wf el9 u20 u22

---

bootstrap/configure_environment.sh

ssh won't work id `.ssh/authorized_keys` is work readable

bootstrap: set correct permissions on .ssh/authorized_keys

---

collections/monitoring/roles/grafana/README.md
collections/monitoring/roles/grafana/tasks/dashboards.yml
collections/monitoring/roles/grafana/vars/main.yml

Avoid unnecessary handlers when no dashboard has changed.
This allows role idempotence.

monitoring/grafana: use correct dashboard file permission

---

collections/high_availability/roles/pcs/README.md
collections/high_availability/roles/pcs/tasks/RedHat/firewall.yml
collections/high_availability/roles/pcs/tasks/Ubuntu/before_create.yml
collections/high_availability/roles/pcs/tasks/Ubuntu/firewall.yml
collections/high_availability/roles/pcs/tasks/main.yml
collections/high_availability/roles/pcs/vars/RedHat.yml
collections/high_availability/roles/pcs/vars/Ubuntu.yml
collections/high_availability/roles/pcs/vars/Ubuntu_20.yml
collections/high_availability/roles/pcs/vars/main.yml

- Add support for pacemaker in Ubuntu
- Tested on RHEL8, Ubuntu 20.04, Ubuntu 22.04
- Added new "Known Issues" section in the README for a potential risk on Ubuntu

high_availability/pcs: Add Ubuntu support

---

collections/monitoring/roles/prometheus/README.md
collections/monitoring/roles/prometheus/defaults/main.yml
collections/monitoring/roles/prometheus/tasks/server.yml
collections/monitoring/roles/prometheus/tasks/server_security.yml
collections/monitoring/roles/prometheus/templates/prometheus.yml.j2
collections/monitoring/roles/prometheus/templates/web.yml.j2
collections/monitoring/roles/prometheus/vars/main.yml

Securing Prometheus API and UI endpoints using tls encryption and basic auth

monitoring/prometheus: Support TLS encryption and Basic authentication

---

collections/monitoring/roles/grafana/README.md
collections/monitoring/roles/grafana/defaults/main.yml
collections/monitoring/roles/grafana/tasks/install.yml
collections/monitoring/roles/grafana/vars/main.yml

Added the ability to install a recent version of grafana from the Grafana project

monitoring/grafana: Install a recent version of Grafana

---

collections/infrastructure/roles/dhcp_server/templates/dhcpd.networks.conf.j2

fix: ntp4 instead of dns4

---

collections/infrastructure/roles/dns_server/README.md

Add dns_server_recursion on Readme.md documentation.

Add dns_server_recursion on Readme.md

---

collections/hpc/roles/slurm/README.md
collections/hpc/roles/slurm/defaults/main.yml
collections/hpc/roles/slurm/tasks/compute_configfull.yml
collections/hpc/roles/slurm/templates/acct_gather.conf.j2
collections/hpc/roles/slurm/templates/slurm.conf.j2
collections/hpc/roles/slurm/vars/main.yml

Used for energy consumption accounting, for interconnect network traffic accounting, for filesystem traffic accounting or for detailed job profiling.

hpc/slurm: Added acct_gather plugin configuration

---

collections/monitoring/roles/grafana/README.md
collections/monitoring/roles/grafana/tasks/datasources.yml
collections/monitoring/roles/grafana/vars/main.yml

Used to set parameters such as timeInterval

monitoring/grafana: Added additional_json_data variable in datasource

---

collections/high_availability/roles/haproxy/README.md
collections/high_availability/roles/haproxy/defaults/main.yml
collections/high_availability/roles/haproxy/handlers/main.yml
collections/high_availability/roles/haproxy/tasks/main.yml
collections/high_availability/roles/haproxy/templates/haproxy.cfg.j2
collections/high_availability/roles/haproxy/templates/listen.conf.j2

Add TCP mode for haproxy. Made this mode the default and changed README examples accordingly (http mode). Tell me if I'd rather set http mode the default.

ha/haproxy: add tcp mode

---

collections/monitoring/galaxy.yml
collections/monitoring/roles/prometheus/README.md
collections/monitoring/roles/prometheus/tasks/client.yml
collections/monitoring/roles/prometheus/vars/main.yml

Added a condition in the prometheus role, prevents error when an exporter has no service parameter.

Fix prometheus service item

---

collections/commons/plugins/vars/core.py
collections/hpc/roles/slurm/README.md
collections/infrastructure/roles/access_control/README.md
collections/infrastructure/roles/conman/README.md
collections/infrastructure/roles/dhcp_server/README.md
collections/infrastructure/roles/dns_server/README.md
collections/infrastructure/roles/hosts_file/README.md
collections/infrastructure/roles/kernel_config/README.md
collections/infrastructure/roles/nic/README.md
collections/infrastructure/roles/powerman/README.md
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/ssh_client/README.md
collections/infrastructure/roles/ssh_remote_keys/README.md
collections/infrastructure/roles/time/README.md
collections/logging/roles/rsyslog/README.md
resources/bb_core.yml
resources/data_model.md

Update data model to match BB 2.0.0 new inventory format.
Project sprint 1
- [NA] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- [NA] Update changelog inside role README.md
- [NA] If not present, please also add your name in the related collection authors list in galaxy.yml

Update data_model to 2.0.0

---

.github/workflows/deb11.yml
.github/workflows/deb12.yml
.github/workflows/el8.yml
.github/workflows/el9.yml
.github/workflows/lp15.yml
.github/workflows/u20.yml
.github/workflows/u22.yml
collections/infrastructure/galaxy.yml
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/defaults/main.yml
collections/infrastructure/roles/pxe_stack/templates/Debian/preseed.cfg.j2
collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2
collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2
collections/infrastructure/roles/pxe_stack/templates/Ubuntu/user-data.j2
collections/infrastructure/roles/pxe_stack/vars/main.yml
collections/infrastructure/roles/repositories/README.md
collections/infrastructure/roles/repositories/defaults/main.yml
collections/infrastructure/roles/repositories/tasks/Debian/main.yml
collections/infrastructure/roles/repositories/tasks/RedHat/main.yml
collections/infrastructure/roles/repositories/tasks/Suse/main.yml
collections/infrastructure/roles/repositories/tasks/Ubuntu/main.yml
collections/infrastructure/roles/repositories/tasks/main.yml
collections/infrastructure/roles/repositories/vars/main.yml

Update repositories role and pxe_stack role to better handle repos (simplify repositories and move native removal to pxe_stack).
Also deactivated gpgkey check in Ubuntu because it currently does not comply with simple url format.
Added repositories role usage into checks too.

BB4 - Improve repositories

---

collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/templates/DGX/equipment_profile_dgxos.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Debian/equipment_profile_preseed.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/RedHat/equipment_profile_ks.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Suse/equipment_profile_autoyast.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Trash/configuration_opensuse.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Trash/configuration_ubuntu.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Trash/equipment_profile.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Ubuntu/equipment_profile_cloud-init.ipxe.j2
collections/infrastructure/roles/pxe_stack/templates/Ubuntu/equipment_profile_preseed.ipxe.j2
collections/infrastructure/roles/pxe_stack/vars/main.yml

Replace any occurrence of hard-coded string 'equipment_' with the use of the variable bb_core_equipment_naming.

use var bb_core_equipment_naming instead of hard-coded string 'equipment_'

---

collections/infrastructure/roles/dns_client/README.md
collections/infrastructure/roles/dns_client/templates/resolv.conf.j2
collections/infrastructure/roles/dns_client/vars/main.yml

Fix dns_client nameserver list variable name

infrastructure_dns_client: fix nameserver list

---

collections/infrastructure/galaxy.yml
collections/infrastructure/roles/dhcp_server/README.md
collections/infrastructure/roles/dhcp_server/templates/dhcpd.conf.j2
collections/infrastructure/roles/dhcp_server/vars/main.yml

See related issue https://github.com/bluebanquise/bluebanquise/issues/862

BB-16 - Fix double character in dhcp server

---

collections/hardware/galaxy.yml
collections/hardware/roles/interconnect/README.md
collections/hardware/roles/interconnect/tasks/ofed/RedHat/client.yml
collections/hardware/roles/interconnect/tasks/ofed/RedHat/main.yml
collections/hardware/roles/interconnect/tasks/ofed/RedHat/subnet_manager.yml
collections/hardware/roles/interconnect/vars/main.yml

Fix bad variables names
Fix missing services BB 2 and 3 format
Linked to issue #869

BB-19 - Fix interconnect role

---

bootstrap/online_bootstrap.sh

BB-25 - Add uid gid to bootstrap

---

collections/infrastructure/galaxy.yml
collections/infrastructure/roles/dns_server/README.md
collections/infrastructure/roles/dns_server/templates/forward.j2
collections/infrastructure/roles/dns_server/templates/reverse.j2
collections/infrastructure/roles/dns_server/vars/main.yml
documentation/deploy_cluster.rst

BB-27 - Fix extended names for DNS server

---

collections/high_availability/roles/pcs/README.md
collections/high_availability/roles/pcs/vars/main.yml

Hello,
Some changes to the readme, which hadn't been updated for a while.
Best,

pcs role README.md update

---

collections/commons/galaxy.yml
collections/containers/galaxy.yml
collections/file_systems/galaxy.yml
collections/hardware/galaxy.yml
collections/high_availability/galaxy.yml
collections/hpc/galaxy.yml
collections/infrastructure/galaxy.yml
collections/logging/galaxy.yml
collections/monitoring/galaxy.yml
collections/security/galaxy.yml

Update galaxies to BB3 version

HF-11 - Update all galaxy to 3

---

collections/infrastructure/galaxy.yml
collections/infrastructure/roles/ssh_client/README.md
collections/infrastructure/roles/ssh_client/templates/config.j2
collections/infrastructure/roles/ssh_client/vars/main.yml

Fix ssh_client_userknownhostsfile host_vars inside the `config.j2` template:
```
{% if host_vars['ssh_client_userknownhostsfile'] is defined and host_vars['ssh_client_userknownhostsfile'] is not none %}
UserKnownHostsFile {{ host_vars['ssh_client_userknownhostsfile'] }}
{% endif %}
```
https://github.com/bluebanquise/bluebanquise/issues/901

fix (ssh_client): fix ssh_client_userknownhostsfile host_vars

---

collections/monitoring/galaxy.yml
collections/monitoring/roles/prometheus/README.md
collections/monitoring/roles/prometheus/templates/exporter.service.j2
collections/monitoring/roles/prometheus/vars/main.yml

BB-32 - Add more services tuning for prometheus exporters

---

collections/infrastructure/galaxy.yml
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/tasks/tools/Clonezilla.yml
collections/infrastructure/roles/pxe_stack/vars/main.yml

- Add missing directory in `collections/infrastructure/roles/pxe_stack/tasks/tools/Clonezilla.yml`
#913

[infrastructure/roles/pxe_stack] Add missing clonezilla directory

---

collections/infrastructure/galaxy.yml
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/templates/Debian/preseed.cfg.j2
collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2
collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2
collections/infrastructure/roles/pxe_stack/templates/Ubuntu/user-data.j2
collections/infrastructure/roles/pxe_stack/vars/main.yml
collections/infrastructure/roles/sudoers/README.md
collections/infrastructure/roles/sudoers/tasks/main.yml
collections/infrastructure/roles/sudoers/vars/main.yml

BB-33 - Add packages to autoinstall

---

collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/tasks/main.yml
collections/infrastructure/roles/pxe_stack/vars/main.yml

- [x ] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- x[ ] Update changelog inside role README.md

diskless.yml task must be optional

---

collections/infrastructure/roles/ssh_client/README.md
collections/infrastructure/roles/ssh_client/templates/config.j2
collections/infrastructure/roles/ssh_client/vars/main.yml

- [x ] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- [x ] Update changelog inside role README.md

infrastructure/ssh_client role: set a default network

---

collections/file_systems/galaxy.yml
collections/file_systems/roles/lustre_client/readme.md
collections/file_systems/roles/lustre_client/tasks/main.yml
collections/file_systems/roles/lustre_client/templates/lustre.conf.j2
collections/file_systems/roles/lustre_client/vars/main.yml

Just a new role created to make possible to manage lustre cliente configurations through bluebanquise.
- [ x ] Document introduced changes / variables in role README.md if any
- [ x ] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- [ x ] Update changelog inside role README.md
- [ x ] If not present, please also add your name in the related collection authors list in galaxy.yml

Add Lustre Client role

---

collections/monitoring/galaxy.yml
collections/monitoring/roles/prometheus/README.md
collections/monitoring/roles/prometheus/tasks/client.yml
collections/monitoring/roles/prometheus/tasks/server_alertmanager.yml
collections/monitoring/roles/prometheus/tasks/server_ipmi_exporter.yml
collections/monitoring/roles/prometheus/tasks/server_karma.yml
collections/monitoring/roles/prometheus/tasks/server_prometheus.yml
collections/monitoring/roles/prometheus/tasks/server_snmp_exporter.yml
collections/monitoring/roles/prometheus/vars/main.yml

BB-38 - Fix services rights

---

bootstrap.sh

fix bootstrap.sh

---

collections/infrastructure/roles/nic/README.md
collections/infrastructure/roles/nic/defaults/main.yml
collections/infrastructure/roles/nic/tasks/RedHat/main.yml
collections/infrastructure/roles/nic/tasks/Suse/main.yml
collections/infrastructure/roles/nic/vars/main.yml

Fix for feature request #956 
#956
- [x ] Increment role version in vars/main.yml (a.b.c: +1 to b for a feature added, +1 to c for a bug fix)
- [x ] Update changelog inside role README.md

make the connection restart timeout configurable

---

README.md
collections/infrastructure/galaxy.yml
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2
collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2
collections/infrastructure/roles/pxe_stack/vars/main.yml

Fix some changes, as leads to unstability.

BB-39-HOTFIX

---

.github/workflows/el8.yml
collections/infrastructure/galaxy.yml
collections/infrastructure/roles/pxe_stack/README.md
collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2
collections/infrastructure/roles/pxe_stack/vars/main.yml
resources/docker/Dockerfile_OpenSUSELeap_15_systemd

Fix multiple small issues within autoyast:
- iso repo was kept so remove it
- SLE repos were not added so adding them
- debug script parameter is deprecated

Fix opensuse autoyast file

---

collections/file_systems/galaxy.yml
collections/file_systems/roles/lustre_client/readme.md
collections/file_systems/roles/lustre_client/templates/lustre.conf.j2
collections/file_systems/roles/lustre_client/vars/main.yml

Just add support for multi-rail configuration on the LNET, if there is more than one interface into the same network.

add support for multi-rail on LNET configuration

---

collections/infrastructure/README.md
collections/infrastructure/galaxy.yml
collections/infrastructure/roles/custom_packages/README.md
collections/infrastructure/roles/custom_packages/tasks/main.yml

Creation of custom_packages role, to manage the installation of packages that are not already handled by other roles.

Add custom_packages role

---

collections/infrastructure/roles/rasdaemon/files/labels_gigabyte_cer_blade
collections/infrastructure/roles/rasdaemon/tasks/main.yml

Added task to copy all "labels_*" named files over to rasdaemon config folder.

Feat: rasdaemon: Added gigabyte dimm labels

---

CHANGELOG
README.md
collections/infrastructure/galaxy.yml
collections/infrastructure/plugins/vars/core.py
resources/bb_core.yml

Fix a critical issue I introduced in 3.2.0 core, related to main interface and main address.

BB-51 - Fix critical error in core

---

collections/infrastructure/roles/prometheus/README.md
collections/infrastructure/roles/prometheus/defaults/main.yml
collections/infrastructure/roles/prometheus/handlers/main.yml
collections/infrastructure/roles/prometheus/tasks/client.yml
collections/infrastructure/roles/prometheus/tasks/server_alertmanager.yml
collections/infrastructure/roles/prometheus/tasks/server_ipmi_exporter.yml
collections/infrastructure/roles/prometheus/tasks/server_karma.yml
collections/infrastructure/roles/prometheus/tasks/server_prometheus.yml
collections/infrastructure/roles/prometheus/tasks/server_snmp_exporter.yml
collections/infrastructure/roles/prometheus/templates/karma.yml.j2
collections/infrastructure/roles/prometheus/templates/prometheus.yml.j2
collections/infrastructure/roles/prometheus/vars/main.yml
tutorials/docs/sysadmin_servers_farm_deployment.md

- Handler improvements
- Prometheus prefix
- Alertmanager prefix
- Karma prefix
- Reverse proxy support
- TSDB Storage path and retention time support

[FEAT][Monitoring] Features for Monitoring

---

collections/infrastructure/roles/custom_packages/README.md
collections/infrastructure/roles/custom_packages/tasks/main.yml

I removed the braces in the task.yml
#1042

Fix issue in role custom_packages

---

CHANGELOG
collections/infrastructure/roles/auditd/README.md
collections/infrastructure/roles/auditd/defaults/main.yml
collections/infrastructure/roles/auditd/handlers/main.yml
collections/infrastructure/roles/auditd/tasks/main.yml
collections/infrastructure/roles/auditd/vars/RedHat.yml
collections/infrastructure/roles/auditd/vars/main.yml

Added option to allow logging root commands.

Feat: auditd - Log root commands

---

collections/infrastructure/roles/ssh_client/README.md
collections/infrastructure/roles/ssh_client/defaults/main.yml
collections/infrastructure/roles/ssh_client/templates/config.j2
collections/infrastructure/roles/ssh_client/vars/main.yml

Added the extra following options to ssh client configuration:
ForwardX11Trusted
StrictHostKeyChecking
UseRoaming

Feat: ssh_client - Added more ssh client config options

---

CHANGELOG
collections/infrastructure/roles/podman/README.md
collections/infrastructure/roles/podman/defaults/main.yml
collections/infrastructure/roles/podman/tasks/registry.yml
collections/infrastructure/roles/podman/tasks/registry_encryption.yml
collections/infrastructure/roles/podman/templates/etc/containers/registries.conf.j2
collections/infrastructure/roles/podman/templates/registry.service.j2
collections/infrastructure/roles/podman/vars/main.yml

Adds option to enable encrypted registries.

Feat: podman - podman registry https support

---

collections/infrastructure/galaxy.yml

Bump version of bluebanquise.infrastructure to 3.2.5-smc2.0.3

---

CHANGELOG
collections/infrastructure/roles/http_server/README.md
collections/infrastructure/roles/http_server/defaults/main.yml
collections/infrastructure/roles/http_server/vars/main.yml

* 4/23/25 - lmagdanello - [http_server] Comment out the variables http_server_*_services.
[!1078](https://github.com/bluebanquise/bluebanquise/issues/1078)

fix(http_default): comment out vars http_server_*_services

---

CHANGELOG
collections/infrastructure/roles/pxe_stack/defaults/main.yml
collections/infrastructure/roles/pxe_stack/tasks/diskful/Debian.yml
collections/infrastructure/roles/pxe_stack/tasks/diskful/RedHat.yml
collections/infrastructure/roles/pxe_stack/tasks/diskful/Suse.yml
collections/infrastructure/roles/pxe_stack/tasks/diskful/Ubuntu.yml
collections/infrastructure/roles/pxe_stack/vars/main.yml

Was getting an undefined variable with bb_equipments[item]['type'] , which led to always ending in the default
condition of pxe_stack_hw_equipment_type.

FIX: pxe_stack - when conditional defaulting

---

collections/infrastructure/galaxy.yml

Updated collection version to match release.

Fix: Updated collection version

---

CHANGELOG
collections/infrastructure/roles/lustre_client/readme.md
collections/infrastructure/roles/lustre_client/templates/lustre.conf.j2

Just fixing an issue that when defining multiple LNet, the lustre.conf file was wrongly generated with multiple lines. with this PR, this issue is fixed

lustre_client - Fix issues with multiple-lnet setup
